global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'telemetry-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app:8080']   # nome do container da aplicação