-- =============================================================================
-- ROUTING SERVICE — routing_db
-- Responsável: Rotas planejadas, viagens, desvios, pontos de entrega,
--              cache OSRM, geocoding, ETA dinâmico
-- Porta: 8083
-- =============================================================================

-- O banco é criado pela infraestrutura; a migration atua na conexão atual.
-- =============================================================================
-- SEÇÃO 1 — CACHES LOCAIS (replicados via Kafka)
-- =============================================================================

CREATE TABLE IF NOT EXISTS veiculos_cache (
    id              BIGINT  NOT NULL PRIMARY KEY,
    uuid            CHAR(36) NOT NULL UNIQUE,
    tenant_id       BIGINT  NOT NULL,
    placa           VARCHAR(10) NOT NULL,
    modelo          VARCHAR(255),
    tipo_veiculo    VARCHAR(50) NOT NULL DEFAULT 'CAMINHAO_PESADO',
    consumo_medio   DOUBLE PRECISION,
    pbt_kg          DOUBLE PRECISION,
    ativo           BOOLEAN NOT NULL DEFAULT TRUE,
    sincronizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_vc_tenant ON veiculos_cache (tenant_id);

CREATE TABLE IF NOT EXISTS motoristas_cache (
    id              BIGINT  NOT NULL PRIMARY KEY,
    uuid            CHAR(36) NOT NULL UNIQUE,
    tenant_id       BIGINT  NOT NULL,
    nome            VARCHAR(255) NOT NULL,
    cpf             VARCHAR(14) NOT NULL,
    ativo           BOOLEAN NOT NULL DEFAULT TRUE,
    sincronizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_mc_tenant ON motoristas_cache (tenant_id);

-- =============================================================================
-- SEÇÃO 2 — ROTAS
-- =============================================================================

-- ---------------------------------------------------------------------------
-- TABELA: rotas
-- Rota planejada com dados OSRM completos, paradas, thresholds e status.
-- Esta é a tabela central do routing-service.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS rotas (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                    CHAR(36) NOT NULL UNIQUE DEFAULT (gen_random_uuid()::text),
    tenant_id               BIGINT  NOT NULL,
    nome                    VARCHAR(255) NOT NULL,

    -- ▸ ORIGEM
    origem_nome             VARCHAR(255) NOT NULL,
    origem_latitude         DOUBLE PRECISION NOT NULL,
    origem_longitude        DOUBLE PRECISION NOT NULL,
    origem_endereco         VARCHAR(500),
    origem_cep              VARCHAR(10),

    -- ▸ DESTINO
    destino_nome            VARCHAR(255) NOT NULL,
    destino_latitude        DOUBLE PRECISION NOT NULL,
    destino_longitude       DOUBLE PRECISION NOT NULL,
    destino_endereco        VARCHAR(500),
    destino_cep             VARCHAR(10),

    -- ▸ DADOS CALCULADOS PELO OSRM
    distancia_km            DOUBLE PRECISION,
    tempo_estimado_min      INT,
    polyline_encoded        TEXT,
    rota_geojson            JSON,
    pontos_rota             JSON,
    pontos_snap             JSON,
    osrm_request_id         VARCHAR(36),

    -- ▸ PARADAS INTERMEDIÁRIAS
    paradas                 JSON,
    sequencia_otimizada     JSON,
    total_paradas           INT NOT NULL DEFAULT 0,

    -- ▸ ESTIMATIVAS DE CUSTO
    custo_pedagio_est       DECIMAL(10,2),
    custo_combustivel_est   DECIMAL(10,2),
    custo_total_est         DECIMAL(10,2),

    -- ▸ CONFIGURAÇÕES DE DESVIO
    tolerancia_desvio_m     DOUBLE PRECISION NOT NULL DEFAULT 100.0,
    threshold_alerta_m      DOUBLE PRECISION NOT NULL DEFAULT 50.0,
    max_km_extras_alerta    DOUBLE PRECISION NOT NULL DEFAULT 2.0,

    -- ▸ VÍNCULOS
    veiculo_id              BIGINT,
    veiculo_uuid            CHAR(36),
    motorista_id            BIGINT,
    motorista_uuid          CHAR(36),
    carga_uuid              CHAR(36),

    -- ▸ DATAS
    data_inicio_plan        TIMESTAMP,
    data_fim_plan           TIMESTAMP,
    data_inicio_real        TIMESTAMP,
    data_fim_real           TIMESTAMP,

    -- ▸ DOCUMENTAÇÃO FISCAL
    mdfe_chave              VARCHAR(50),
    cte_chave               VARCHAR(50),
    ciot_codigo             VARCHAR(30),

    -- ▸ PERFIL OSRM
    perfil_osrm             VARCHAR(50) NOT NULL DEFAULT 'CAMINHAO',

    -- ▸ STATUS
    status                  VARCHAR(50) NOT NULL DEFAULT 'PLANEJADA',
    motivo_cancelamento     TEXT,

    -- ▸ CONTROLE
    ativa                   BOOLEAN NOT NULL DEFAULT TRUE,
    criado_por              VARCHAR(255),
    criado_em               TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

 CONSTRAINT fk_rota_veiculo FOREIGN KEY (veiculo_id) REFERENCES veiculos_cache(id) ON DELETE SET NULL,
 CONSTRAINT fk_rota_motorista FOREIGN KEY (motorista_id) REFERENCES motoristas_cache(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_rota_tenant ON rotas (tenant_id);
CREATE INDEX IF NOT EXISTS idx_rota_status ON rotas (status);
CREATE INDEX IF NOT EXISTS idx_rota_veiculo ON rotas (veiculo_id);
CREATE INDEX IF NOT EXISTS idx_rota_motorista ON rotas (motorista_id);
CREATE INDEX IF NOT EXISTS idx_rota_ativa ON rotas (ativa);
CREATE INDEX IF NOT EXISTS idx_rota_datas ON rotas (data_inicio_plan, data_fim_plan);
CREATE INDEX IF NOT EXISTS idx_rota_uuid ON rotas (uuid);

-- =============================================================================
-- SEÇÃO 3 — VIAGENS
-- =============================================================================

-- ---------------------------------------------------------------------------
-- TABELA: viagens
-- Execução real de uma rota. Contém o estado em tempo real da viagem ativa.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS viagens (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                    CHAR(36) NOT NULL UNIQUE DEFAULT (gen_random_uuid()::text),
    tenant_id               BIGINT  NOT NULL,
    rota_id                 BIGINT ,

    -- Vínculos
    veiculo_id              BIGINT ,
    veiculo_uuid            CHAR(36) NOT NULL,
    motorista_id            BIGINT ,
    motorista_uuid          CHAR(36),
    carga_uuid              CHAR(36),

    -- Datas
    data_saida_plan         TIMESTAMP,
    data_saida_real         TIMESTAMP,
    data_chegada_plan       TIMESTAMP,
    data_chegada_real       TIMESTAMP,
    eta_atual               TIMESTAMP,
    eta_atualizado_em       TIMESTAMP,

    -- Métricas reais
    distancia_real_km       DOUBLE PRECISION NOT NULL DEFAULT 0,
    consumo_real_l          DOUBLE PRECISION NOT NULL DEFAULT 0,
    km_fora_rota            DOUBLE PRECISION NOT NULL DEFAULT 0,
    velocidade_media        DOUBLE PRECISION,
    velocidade_maxima       DOUBLE PRECISION,

    -- Última posição conhecida
    ultima_lat              DOUBLE PRECISION,
    ultima_lng              DOUBLE PRECISION,
    ultima_posicao_em       TIMESTAMP,

    -- Resumo de ocorrências
    total_desvios           INT NOT NULL DEFAULT 0,
    total_alertas           INT NOT NULL DEFAULT 0,
    total_paradas           INT NOT NULL DEFAULT 0,
    tempo_ocioso_min        INT NOT NULL DEFAULT 0,
    frenagens_bruscas       INT NOT NULL DEFAULT 0,
    excessos_velocidade     INT NOT NULL DEFAULT 0,

    -- Score
    score_viagem            INT NOT NULL DEFAULT 1000,

    -- Status
    status                  VARCHAR(50) NOT NULL DEFAULT 'PLANEJADA',
    motivo_cancelamento     TEXT,

    criado_em               TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

 CONSTRAINT fk_viagem_rota FOREIGN KEY (rota_id) REFERENCES rotas(id) ON DELETE SET NULL,
 CONSTRAINT fk_viagem_veiculo FOREIGN KEY (veiculo_id) REFERENCES veiculos_cache(id) ON DELETE SET NULL,
 CONSTRAINT fk_viagem_motorista FOREIGN KEY (motorista_id) REFERENCES motoristas_cache(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_viagem_tenant ON viagens (tenant_id);
CREATE INDEX IF NOT EXISTS idx_viagem_rota ON viagens (rota_id);
CREATE INDEX IF NOT EXISTS idx_viagem_veiculo ON viagens (veiculo_id);
CREATE INDEX IF NOT EXISTS idx_viagem_motorista ON viagens (motorista_id);
CREATE INDEX IF NOT EXISTS idx_viagem_status ON viagens (status);
CREATE INDEX IF NOT EXISTS idx_viagem_datas ON viagens (data_saida_real, data_chegada_real);
CREATE INDEX IF NOT EXISTS idx_viagem_uuid ON viagens (uuid);

-- =============================================================================
-- SEÇÃO 4 — DESVIOS E PONTOS DE ENTREGA
-- =============================================================================

-- ---------------------------------------------------------------------------
-- TABELA: desvios_rota
-- Cada desvio detectado durante a viagem.
-- O telemetry-service envia eventos via Kafka; este serviço persiste o histórico.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS desvios_rota (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id                   BIGINT  NOT NULL,
    viagem_id                   BIGINT  NOT NULL,
    rota_id                     BIGINT  NOT NULL,
    veiculo_uuid                CHAR(36) NOT NULL,

    -- Posição do desvio
    latitude_desvio             DOUBLE PRECISION NOT NULL,
    longitude_desvio            DOUBLE PRECISION NOT NULL,
    velocidade_kmh              DOUBLE PRECISION,
    distancia_metros            DOUBLE PRECISION NOT NULL,

    -- Ponto de referência na rota
    lat_ponto_mais_proximo      DOUBLE PRECISION,
    lng_ponto_mais_proximo      DOUBLE PRECISION,
    nome_via_desvio             VARCHAR(255),
    nome_via_rota               VARCHAR(255),

    -- Período do desvio
    data_hora_desvio            TIMESTAMP NOT NULL,
    data_hora_retorno           TIMESTAMP,
    duracao_min                 INT,
    km_extras                   DOUBLE PRECISION NOT NULL DEFAULT 0,

    -- Gestão
    alerta_enviado              BOOLEAN NOT NULL DEFAULT FALSE,
    alerta_id                   BIGINT,
    resolvido                   BOOLEAN NOT NULL DEFAULT FALSE,
    motivo_motorista            VARCHAR(255),
    aprovado_gestor             BOOLEAN,

    criado_em                   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

 CONSTRAINT fk_dr_viagem FOREIGN KEY (viagem_id) REFERENCES viagens(id) ON DELETE CASCADE,
 CONSTRAINT fk_dr_rota FOREIGN KEY (rota_id) REFERENCES rotas(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_dr_viagem ON desvios_rota (viagem_id);
CREATE INDEX IF NOT EXISTS idx_dr_rota ON desvios_rota (rota_id);
CREATE INDEX IF NOT EXISTS idx_dr_data ON desvios_rota (data_hora_desvio);
CREATE INDEX IF NOT EXISTS idx_dr_resolvido ON desvios_rota (resolvido);

-- ---------------------------------------------------------------------------
-- TABELA: pontos_entrega
-- Cada parada/entrega realizada na viagem com proof of delivery.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pontos_entrega (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           BIGINT  NOT NULL,
    viagem_id           BIGINT  NOT NULL,
    sequencia           INT NOT NULL,

    -- Dados do ponto
    nome                VARCHAR(255),
    endereco            VARCHAR(500),
    latitude            DOUBLE PRECISION NOT NULL,
    longitude           DOUBLE PRECISION NOT NULL,
    tipo                VARCHAR(50) NOT NULL DEFAULT 'ENTREGA',

    -- Janela de tempo
    janela_inicio       TIMESTAMP,
    janela_fim          TIMESTAMP,

    -- Execução real
    eta_calculado       TIMESTAMP,
    chegada_real        TIMESTAMP,
    saida_real          TIMESTAMP,
    dentro_janela       BOOLEAN,

    -- Proof of Delivery
    status              VARCHAR(50) NOT NULL DEFAULT 'PENDENTE',
    destinatario_nome   VARCHAR(255),
    assinatura_path     VARCHAR(500),
    foto_entrega_path   VARCHAR(500),
    ocorrencia          TEXT,
    codigo_rastreio     VARCHAR(50),
    nfe_chave           VARCHAR(50),

    criado_em           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

 CONSTRAINT fk_pe_viagem FOREIGN KEY (viagem_id) REFERENCES viagens(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_pe_viagem ON pontos_entrega (viagem_id);
CREATE INDEX IF NOT EXISTS idx_pe_seq ON pontos_entrega (viagem_id, sequencia);
CREATE INDEX IF NOT EXISTS idx_pe_status ON pontos_entrega (status);

-- =============================================================================
-- SEÇÃO 5 — CACHE OSRM E GEOCODING
-- =============================================================================

-- ---------------------------------------------------------------------------
-- TABELA: osrm_route_cache
-- Cache de rotas calculadas para evitar chamadas repetidas ao OSRM.
-- Key = MD5(origem_lat:origem_lng:destino_lat:destino_lng:perfil)
-- TTL recomendado: 7 dias (rotas mudam com obras/updates do mapa)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS osrm_route_cache (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cache_key       VARCHAR(64) NOT NULL UNIQUE,
    perfil          VARCHAR(50) NOT NULL DEFAULT 'CAMINHAO',

    -- Origem e destino (para debug e recalcular se necessário)
    lat_origem      DOUBLE PRECISION NOT NULL,
    lng_origem      DOUBLE PRECISION NOT NULL,
    lat_destino     DOUBLE PRECISION NOT NULL,
    lng_destino     DOUBLE PRECISION NOT NULL,

    -- Resultado OSRM
    distancia_km    DOUBLE PRECISION NOT NULL,
    duracao_min     INT NOT NULL,
    polyline        TEXT,
    geojson         JSON,
    instrucoes      JSON,

    -- Metadados
    hits            INT NOT NULL DEFAULT 1,
    criado_em       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expira_em       TIMESTAMP NOT NULL

);
CREATE INDEX IF NOT EXISTS idx_osrm_key ON osrm_route_cache (cache_key);
CREATE INDEX IF NOT EXISTS idx_osrm_expira ON osrm_route_cache (expira_em);

-- ---------------------------------------------------------------------------
-- TABELA: geocoding_cache
-- Cache de geocoding direto e reverso para evitar chamadas externas.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS geocoding_cache (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat_arred       DECIMAL(7,4) NOT NULL,
    lng_arred       DECIMAL(7,4) NOT NULL,
    pais            VARCHAR(100),
    estado          VARCHAR(100),
    cidade          VARCHAR(200),
    bairro          VARCHAR(200),
    logradouro      VARCHAR(300),
    cep             VARCHAR(10),
    nome_local      VARCHAR(255),
    tipo_local      VARCHAR(50),
    is_urbano       BOOLEAN,
    precisao_metros INT,
    fonte           VARCHAR(50) NOT NULL DEFAULT 'NOMINATIM',
    consulta_em     TIMESTAMP NOT NULL,
    expira_em       TIMESTAMP NOT NULL,
    CONSTRAINT uk_geocoding_coords UNIQUE (lat_arred, lng_arred)
);
CREATE INDEX IF NOT EXISTS idx_geo_expira ON geocoding_cache (expira_em);

-- =============================================================================
-- SEÇÃO 6 — HISTÓRICO E ANÁLISE
-- =============================================================================

-- ---------------------------------------------------------------------------
-- TABELA: historico_trajeto_viagem
-- Trajetória real simplificada da viagem para relatório pós-viagem.
-- Versão comprimida (Douglas-Peucker) — dados completos no telemetry-service.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS historico_trajeto_viagem (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT  NOT NULL,
    viagem_id   BIGINT  NOT NULL,
    segmento    INT NOT NULL,
    trajeto     JSON NOT NULL,
    km_segmento DOUBLE PRECISION NOT NULL DEFAULT 0,
    criado_em   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT fk_htv_viagem FOREIGN KEY (viagem_id) REFERENCES viagens(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_htv_viagem ON historico_trajeto_viagem (viagem_id);
CREATE INDEX IF NOT EXISTS idx_htv_segmento ON historico_trajeto_viagem (viagem_id, segmento);

-- ---------------------------------------------------------------------------
-- TABELA: relatorio_viagem
-- Relatório pós-viagem consolidado gerado ao finalizar a viagem.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS relatorio_viagem (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id               BIGINT  NOT NULL,
    viagem_id               BIGINT  NOT NULL UNIQUE,
    rota_id                 BIGINT ,
    veiculo_uuid            CHAR(36) NOT NULL,
    motorista_uuid          CHAR(36),

    -- Aderência à rota
    aderencia_pct           DOUBLE PRECISION,
    desvios_count           INT NOT NULL DEFAULT 0,
    km_extras_total         DOUBLE PRECISION NOT NULL DEFAULT 0,

    -- Tempo
    duracao_total_min       INT,
    atraso_chegada_min      INT,
    tempo_paradas_min       INT,
    tempo_ocioso_min        INT,

    -- Distância
    km_total                DOUBLE PRECISION,
    km_planejado            DOUBLE PRECISION,
    diferenca_km            DOUBLE PRECISION,

    -- Combustível
    litros_consumidos       DOUBLE PRECISION,
    custo_combustivel       DECIMAL(10,2),
    consumo_medio           DOUBLE PRECISION,

    -- Comportamento
    score_final             INT,
    frenagens_bruscas       INT,
    excessos_velocidade     INT,
    aceleracoes_bruscas     INT,

    -- Entregas
    entregas_total          INT,
    entregas_sucesso        INT,
    entregas_falhas         INT,
    entregas_no_prazo       INT,

    -- PDF gerado
    pdf_path                VARCHAR(500),
    gerado_em               TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

 CONSTRAINT fk_rv_viagem FOREIGN KEY (viagem_id) REFERENCES viagens(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_rv_tenant ON relatorio_viagem (tenant_id);
CREATE INDEX IF NOT EXISTS idx_rv_veiculo ON relatorio_viagem (veiculo_uuid);

-- =============================================================================
-- SEÇÃO 7 — VIEWS ÚTEIS
-- =============================================================================

-- Viagens ativas com dados de veículo e motorista
CREATE OR REPLACE VIEW vw_viagens_ativas AS
SELECT
    v.*,
    vc.placa,
    vc.modelo,
    vc.tipo_veiculo,
    mc.nome AS motorista_nome,
    r.origem_nome,
    r.destino_nome,
    r.distancia_km AS distancia_planejada_km
FROM viagens v
LEFT JOIN veiculos_cache  vc ON v.veiculo_id   = vc.id
LEFT JOIN motoristas_cache mc ON v.motorista_id = mc.id
LEFT JOIN rotas r              ON v.rota_id      = r.id
WHERE v.status IN ('PLANEJADA','EM_ANDAMENTO','PAUSADA');

-- Resumo de desvios por rota
CREATE OR REPLACE VIEW vw_desvios_pendentes AS
SELECT
    d.*,
    v.uuid AS viagem_uuid,
    r.nome AS rota_nome
FROM desvios_rota d
LEFT JOIN viagens v ON d.viagem_id = v.id
LEFT JOIN rotas   r ON d.rota_id   = r.id
WHERE d.resolvido = FALSE
ORDER BY d.data_hora_desvio DESC;
