spring.application.name=routing-service

server.port=8082


spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# RN-TEL-003: Snap-to-road OSRM
osrm.api.url=https://router.project-osrm.org/nearest/v1/driving/%f,%f
snap.cache.ttl.hours=24
snap.coordinate.rounding=3

# Configurações Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379