-- =============================================================================
-- AUTH SERVICE — auth_db
-- Responsável: Autenticação JWT, RBAC, MFA, SSO, refresh tokens, auditoria
-- Porta: 8081
-- =============================================================================

CREATE SCHEMA IF NOT EXISTS auth_db;
SET search_path TO auth_db, public;
-- ---------------------------------------------------------------------------
-- TABELA: tenants
-- Registro de cada transportadora/empresa contratante do SaaS
-- ---------------------------------------------------------------------------
CREATE TABLE tenants (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid          CHAR(36) NOT NULL UNIQUE DEFAULT (gen_random_uuid()::text),
    nome          VARCHAR(255) NOT NULL,
    cnpj          VARCHAR(20)  NOT NULL UNIQUE,
    plano         VARCHAR(50) NOT NULL DEFAULT 'STARTER',
    status        VARCHAR(50) NOT NULL DEFAULT 'TRIAL',
    max_veiculos  INT NOT NULL DEFAULT 10,
    trial_expira  DATE,
    criado_em     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_tenant_cnpj ON tenants (cnpj);
CREATE INDEX IF NOT EXISTS idx_tenant_status ON tenants (status);
CREATE INDEX IF NOT EXISTS idx_tenant_plano ON tenants (plano);

-- ---------------------------------------------------------------------------
-- TABELA: roles
-- Papéis globais do RBAC
-- ---------------------------------------------------------------------------
CREATE TABLE roles (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        VARCHAR(50) NOT NULL UNIQUE,
    descricao   VARCHAR(255),
    nivel       INT NOT NULL DEFAULT 5
);

INSERT INTO roles (nome, descricao, nivel) VALUES
    ('SUPER_ADMIN',   'Acesso total à plataforma, todos os tenants', 1),
    ('ADMIN_TENANT',  'Administrador do tenant próprio',             2),
    ('GESTOR',        'Gestor de frota designada',                   3),
    ('OPERADOR',      'Leitura e resposta a alertas',                4),
    ('MOTORISTA',     'Acesso apenas ao app mobile',                 5),
    ('API_CLIENT',    'Integrações externas via OAuth2',             5);

-- ---------------------------------------------------------------------------
-- TABELA: permissoes
-- Permissões granulares por recurso/ação
-- ---------------------------------------------------------------------------
CREATE TABLE permissoes (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recurso  VARCHAR(100) NOT NULL,
    acao     VARCHAR(50)  NOT NULL,
    descricao VARCHAR(255),
    CONSTRAINT uk_recurso_acao UNIQUE (recurso, acao)
);

-- ---------------------------------------------------------------------------
-- TABELA: role_permissoes
-- Vínculo N:N entre roles e permissões
-- ---------------------------------------------------------------------------
CREATE TABLE role_permissoes (
    role_id      BIGINT  NOT NULL,
    permissao_id BIGINT  NOT NULL,
    PRIMARY KEY (role_id, permissao_id),
 CONSTRAINT fk_rp_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
 CONSTRAINT fk_rp_permissao FOREIGN KEY (permissao_id) REFERENCES permissoes(id) ON DELETE CASCADE
);

-- ---------------------------------------------------------------------------
-- TABELA: usuarios
-- Usuários do sistema (gestores, operadores, motoristas, APIs)
-- ---------------------------------------------------------------------------
CREATE TABLE usuarios (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                CHAR(36) NOT NULL UNIQUE DEFAULT (gen_random_uuid()::text),
    tenant_id           BIGINT  NOT NULL,
    nome                VARCHAR(255) NOT NULL,
    email               VARCHAR(255) NOT NULL,
    senha_hash          VARCHAR(255) NOT NULL,
    cpf                 VARCHAR(14),
    telefone            VARCHAR(20),
    role_id             BIGINT  NOT NULL,
    ativo               BOOLEAN NOT NULL DEFAULT TRUE,
    email_verificado    BOOLEAN NOT NULL DEFAULT FALSE,
    mfa_habilitado      BOOLEAN NOT NULL DEFAULT FALSE,
    mfa_secret          VARCHAR(64),
    mfa_tipo            VARCHAR(50) DEFAULT 'TOTP',
    ip_whitelist        JSON,
    ultimo_acesso       TIMESTAMP,
    tentativas_login    SMALLINT  NOT NULL DEFAULT 0,
    bloqueado_ate       TIMESTAMP,
    token_recuperacao   VARCHAR(128),
    token_recuperacao_exp TIMESTAMP,
    token_ativacao      VARCHAR(128),
    criado_em           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_usuario_email_tenant UNIQUE (tenant_id, email),
 CONSTRAINT fk_usuario_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
 CONSTRAINT fk_usuario_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_usuario_tenant ON usuarios (tenant_id);
CREATE INDEX IF NOT EXISTS idx_usuario_cpf ON usuarios (cpf);
CREATE INDEX IF NOT EXISTS idx_usuario_role ON usuarios (role_id);

-- ---------------------------------------------------------------------------
-- TABELA: refresh_tokens
-- Tokens de renovação de sessão com TTL de 7 dias
-- ---------------------------------------------------------------------------
CREATE TABLE refresh_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id  BIGINT  NOT NULL,
    tenant_id   BIGINT  NOT NULL,
    token_hash  VARCHAR(255) NOT NULL UNIQUE,
    device_info VARCHAR(255),
    ip_origem   VARCHAR(45),
    expira_em   TIMESTAMP NOT NULL,
    revogado    BOOLEAN NOT NULL DEFAULT FALSE,
    criado_em   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT fk_rt_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_rt_usuario ON refresh_tokens (usuario_id);
CREATE INDEX IF NOT EXISTS idx_rt_expira ON refresh_tokens (expira_em);

-- ---------------------------------------------------------------------------
-- TABELA: api_clients
-- Credenciais OAuth2 para integrações (ERPs, seguradoras)
-- ---------------------------------------------------------------------------
CREATE TABLE api_clients (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     BIGINT  NOT NULL,
    client_id     VARCHAR(64) NOT NULL UNIQUE,
    client_secret VARCHAR(255) NOT NULL,
    nome          VARCHAR(100) NOT NULL,
    scopes        JSON NOT NULL,
    ativo         BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT fk_apiclient_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_apiclient_tenant ON api_clients (tenant_id);

-- ---------------------------------------------------------------------------
-- TABELA: audit_log
-- Log imutável de todas as ações de autenticação
-- ---------------------------------------------------------------------------
CREATE TABLE audit_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT ,
    usuario_id  BIGINT ,
    email       VARCHAR(255),
    acao        VARCHAR(50) NOT NULL,
    ip          VARCHAR(45) NOT NULL,
    user_agent  VARCHAR(512),
    dados       JSON,
    sucesso     BOOLEAN NOT NULL,
    criado_em   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_audit_tenant ON audit_log (tenant_id);
CREATE INDEX IF NOT EXISTS idx_audit_usuario ON audit_log (usuario_id);
CREATE INDEX IF NOT EXISTS idx_audit_acao ON audit_log (acao);
CREATE INDEX IF NOT EXISTS idx_audit_criado ON audit_log (criado_em);

-- ---------------------------------------------------------------------------
-- TABELA: sessoes_ativas
-- Controle de sessões concorrentes por usuário
-- ---------------------------------------------------------------------------
CREATE TABLE sessoes_ativas (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id  BIGINT  NOT NULL,
    tenant_id   BIGINT  NOT NULL,
    jti         VARCHAR(64) NOT NULL UNIQUE,
    ip          VARCHAR(45),
    device_info VARCHAR(255),
    expira_em   TIMESTAMP NOT NULL,
    criado_em   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT fk_sessao_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_sessao_usuario ON sessoes_ativas (usuario_id);
CREATE INDEX IF NOT EXISTS idx_sessao_expira ON sessoes_ativas (expira_em);
