-- =============================================================================
-- VEHICLE SERVICE — vehicle_db
-- Responsável: Veículos, motoristas, frota, documentos, TPMS, histórico
-- Porta: 8084 / 8085 (driver_service compartilha o mesmo schema ou banco separado)
-- =============================================================================

CREATE SCHEMA IF NOT EXISTS vehicle_db;
SET search_path TO vehicle_db, public;
-- ---------------------------------------------------------------------------
-- TABELA: veiculos
-- Cadastro completo dos veículos da frota por tenant
-- ---------------------------------------------------------------------------
CREATE TABLE veiculos (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                  CHAR(36) NOT NULL UNIQUE DEFAULT (gen_random_uuid()::text),
    tenant_id             BIGINT  NOT NULL,
    placa                 VARCHAR(10) NOT NULL,
    chassi                VARCHAR(50),
    renavam               VARCHAR(20),
    modelo                VARCHAR(255) NOT NULL,
    marca                 VARCHAR(100) NOT NULL,
    ano_fabricacao        SMALLINT,
    ano_modelo            SMALLINT,
    cor                   VARCHAR(50),
    tipo_veiculo          VARCHAR(50) NOT NULL DEFAULT 'CAMINHAO_PESADO',
    tipo_carroceria       VARCHAR(50),
    capacidade_carga_kg   DOUBLE PRECISION NOT NULL,
    tara_kg               DOUBLE PRECISION,
    eixos                 SMALLINT DEFAULT 2,
    pbt_kg                DOUBLE PRECISION,
    cmt_kg                DOUBLE PRECISION,
    consumo_medio         DOUBLE PRECISION,
    capacidade_tanque_l   DOUBLE PRECISION,
    odometro_atual_km     DOUBLE PRECISION NOT NULL DEFAULT 0,
    horas_motor           DOUBLE PRECISION NOT NULL DEFAULT 0,
    status                VARCHAR(50) NOT NULL DEFAULT 'ATIVO',
    -- Documentação
    rntrc                 VARCHAR(20),
    data_venc_crlv        DATE,
    data_venc_seguro      DATE,
    data_venc_tacografo   DATE,
    data_venc_vistoria    DATE,
    -- Dispositivo IoT vinculado
    device_id             VARCHAR(64) UNIQUE,
    device_imei           VARCHAR(20),
    firmware_versao       VARCHAR(30),
    -- Flags
    tacografo_obrigatorio BOOLEAN NOT NULL DEFAULT FALSE,
    ativo                 BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_veiculo_placa_tenant UNIQUE (tenant_id, placa)
);
CREATE INDEX IF NOT EXISTS idx_veiculo_tenant ON veiculos (tenant_id);
CREATE INDEX IF NOT EXISTS idx_veiculo_status ON veiculos (status);
CREATE INDEX IF NOT EXISTS idx_veiculo_device ON veiculos (device_id);
CREATE INDEX IF NOT EXISTS idx_veiculo_tipo ON veiculos (tipo_veiculo);

-- ---------------------------------------------------------------------------
-- TABELA: motoristas
-- Cadastro completo dos motoristas por tenant
-- ---------------------------------------------------------------------------
CREATE TABLE motoristas (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                  CHAR(36) NOT NULL UNIQUE DEFAULT (gen_random_uuid()::text),
    tenant_id             BIGINT  NOT NULL,
    usuario_uuid          CHAR(36),
    nome                  VARCHAR(255) NOT NULL,
    cpf                   VARCHAR(14) NOT NULL,
    cnh                   VARCHAR(50) NOT NULL,
    categoria_cnh         VARCHAR(10) NOT NULL,
    data_validade_cnh     DATE,
    data_nascimento       DATE,
    telefone              VARCHAR(20),
    email                 VARCHAR(255),
    mopp                  BOOLEAN NOT NULL DEFAULT FALSE,
    data_venc_mopp        DATE,
    aso_valido            BOOLEAN NOT NULL DEFAULT TRUE,
    data_venc_aso         DATE,
    -- Dados bancários (para pagamento, opcional)
    banco_codigo          VARCHAR(10),
    banco_agencia         VARCHAR(10),
    banco_conta           VARCHAR(20),
    pix_chave             VARCHAR(100),
    -- Métricas
    score_comportamento   INT NOT NULL DEFAULT 1000,
    km_total_rodados      DOUBLE PRECISION NOT NULL DEFAULT 0,
    viagens_realizadas    INT NOT NULL DEFAULT 0,
    status                VARCHAR(50) NOT NULL DEFAULT 'ATIVO',
    ativo                 BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_motorista_cpf_tenant UNIQUE (tenant_id, cpf)
);
CREATE INDEX IF NOT EXISTS idx_motorista_tenant ON motoristas (tenant_id);
CREATE INDEX IF NOT EXISTS idx_motorista_cnh ON motoristas (cnh);
CREATE INDEX IF NOT EXISTS idx_motorista_status ON motoristas (status);

-- ---------------------------------------------------------------------------
-- TABELA: veiculo_motorista
-- Histórico de vinculação motorista <-> veículo ao longo do tempo
-- ---------------------------------------------------------------------------
CREATE TABLE veiculo_motorista (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id    BIGINT  NOT NULL,
    veiculo_id   BIGINT  NOT NULL,
    motorista_id BIGINT  NOT NULL,
    data_inicio  TIMESTAMP NOT NULL,
    data_fim     TIMESTAMP,
    ativo        BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT fk_vm_veiculo FOREIGN KEY (veiculo_id) REFERENCES veiculos(id) ON DELETE CASCADE,
 CONSTRAINT fk_vm_motorista FOREIGN KEY (motorista_id) REFERENCES motoristas(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_vm_veiculo ON veiculo_motorista (veiculo_id);
CREATE INDEX IF NOT EXISTS idx_vm_motorista ON veiculo_motorista (motorista_id);
CREATE INDEX IF NOT EXISTS idx_vm_ativo ON veiculo_motorista (ativo);

-- ---------------------------------------------------------------------------
-- TABELA: documentos_veiculo
-- Documentos com controle de vencimento e alertas
-- ---------------------------------------------------------------------------
CREATE TABLE documentos_veiculo (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT  NOT NULL,
    veiculo_id      BIGINT  NOT NULL,
    tipo            VARCHAR(50) NOT NULL,
    numero          VARCHAR(50),
    data_emissao    DATE,
    data_vencimento DATE NOT NULL,
    arquivo_path    VARCHAR(500),
    observacoes     TEXT,
    notificado_30d  BOOLEAN NOT NULL DEFAULT FALSE,
    notificado_7d   BOOLEAN NOT NULL DEFAULT FALSE,
    criado_em       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT fk_docv_veiculo FOREIGN KEY (veiculo_id) REFERENCES veiculos(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_docv_veiculo ON documentos_veiculo (veiculo_id);
CREATE INDEX IF NOT EXISTS idx_docv_vencimento ON documentos_veiculo (data_vencimento);
CREATE INDEX IF NOT EXISTS idx_docv_tipo ON documentos_veiculo (tipo);

-- ---------------------------------------------------------------------------
-- TABELA: documentos_motorista
-- CNH, MOPP, ASO e outros documentos do motorista
-- ---------------------------------------------------------------------------
CREATE TABLE documentos_motorista (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT  NOT NULL,
    motorista_id    BIGINT  NOT NULL,
    tipo            VARCHAR(50) NOT NULL,
    numero          VARCHAR(50),
    data_emissao    DATE,
    data_vencimento DATE NOT NULL,
    arquivo_path    VARCHAR(500),
    observacoes     TEXT,
    notificado_30d  BOOLEAN NOT NULL DEFAULT FALSE,
    notificado_7d   BOOLEAN NOT NULL DEFAULT FALSE,
    criado_em       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT fk_docm_motorista FOREIGN KEY (motorista_id) REFERENCES motoristas(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_docm_motorista ON documentos_motorista (motorista_id);
CREATE INDEX IF NOT EXISTS idx_docm_vencimento ON documentos_motorista (data_vencimento);

-- ---------------------------------------------------------------------------
-- TABELA: pneus
-- Gestão individual de pneus por veículo (integração TPMS)
-- ---------------------------------------------------------------------------
CREATE TABLE pneus (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id            BIGINT  NOT NULL,
    veiculo_id           BIGINT  NOT NULL,
    posicao              VARCHAR(10) NOT NULL,
    marca                VARCHAR(50),
    modelo               VARCHAR(100),
    dimensao             VARCHAR(30),
    dot                  VARCHAR(20),
    km_instalado         DOUBLE PRECISION,
    km_vida_util_est     DOUBLE PRECISION NOT NULL DEFAULT 80000,
    pressao_recomendada  DOUBLE PRECISION NOT NULL,
    pressao_atual        DOUBLE PRECISION,
    temperatura_atual    DOUBLE PRECISION,
    sensor_id_tpms       VARCHAR(30),
    status               VARCHAR(50) NOT NULL DEFAULT 'ATIVO',
    instalado_em         TIMESTAMP,
    criado_em            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT fk_pneu_veiculo FOREIGN KEY (veiculo_id) REFERENCES veiculos(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_pneu_veiculo ON pneus (veiculo_id);
CREATE INDEX IF NOT EXISTS idx_pneu_sensor ON pneus (sensor_id_tpms);

-- ---------------------------------------------------------------------------
-- TABELA: historico_score_motorista
-- Série temporal do score de comportamento (para gráficos e UBI)
-- ---------------------------------------------------------------------------
CREATE TABLE historico_score_motorista (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT  NOT NULL,
    motorista_id    BIGINT  NOT NULL,
    periodo         DATE NOT NULL,
    score           INT NOT NULL,
    frenagens       INT NOT NULL DEFAULT 0,
    aceleracoes     INT NOT NULL DEFAULT 0,
    excessos_vel    INT NOT NULL DEFAULT 0,
    uso_celular     INT NOT NULL DEFAULT 0,
    fadiga          INT NOT NULL DEFAULT 0,
    km_periodo      DOUBLE PRECISION NOT NULL DEFAULT 0,
    criado_em       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_score_motorista_periodo UNIQUE (tenant_id, motorista_id, periodo),
 CONSTRAINT fk_hsc_motorista FOREIGN KEY (motorista_id) REFERENCES motoristas(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_hsc_motorista ON historico_score_motorista (motorista_id);
CREATE INDEX IF NOT EXISTS idx_hsc_periodo ON historico_score_motorista (periodo);

-- ---------------------------------------------------------------------------
-- TABELA: jornadas
-- Controle de jornada Lei 12.619 — integrando com tacógrafo
-- ---------------------------------------------------------------------------
CREATE TABLE jornadas (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           BIGINT  NOT NULL,
    motorista_id        BIGINT  NOT NULL,
    veiculo_id          BIGINT ,
    data_inicio         TIMESTAMP NOT NULL,
    data_fim            TIMESTAMP,
    horas_direcao       DOUBLE PRECISION NOT NULL DEFAULT 0,
    horas_disponivel    DOUBLE PRECISION NOT NULL DEFAULT 0,
    horas_repouso       DOUBLE PRECISION NOT NULL DEFAULT 0,
    horas_extras        DOUBLE PRECISION NOT NULL DEFAULT 0,
    pausas_realizadas   INT NOT NULL DEFAULT 0,
    status              VARCHAR(50) NOT NULL DEFAULT 'ABERTA',
    origem_dado         VARCHAR(50) NOT NULL DEFAULT 'APP',
    alerta_enviado      BOOLEAN NOT NULL DEFAULT FALSE,
    criado_em           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT fk_jornada_motorista FOREIGN KEY (motorista_id) REFERENCES motoristas(id) ON DELETE CASCADE,
 CONSTRAINT fk_jornada_veiculo FOREIGN KEY (veiculo_id) REFERENCES veiculos(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_jornada_motorista ON jornadas (motorista_id);
CREATE INDEX IF NOT EXISTS idx_jornada_data ON jornadas (data_inicio);
CREATE INDEX IF NOT EXISTS idx_jornada_status ON jornadas (status);

-- ---------------------------------------------------------------------------
-- TABELA: geofences
-- Zonas geográficas configuráveis por tenant (círculo ou polígono)
-- ---------------------------------------------------------------------------
CREATE TABLE geofences (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid             CHAR(36) NOT NULL UNIQUE DEFAULT (gen_random_uuid()::text),
    tenant_id        BIGINT  NOT NULL,
    nome             VARCHAR(255) NOT NULL,
    tipo             VARCHAR(50) NOT NULL DEFAULT 'CIRCULO',
    latitude_centro  DOUBLE PRECISION,
    longitude_centro DOUBLE PRECISION,
    raio_metros      DOUBLE PRECISION,
    vertices         JSON,
    tipo_alerta      VARCHAR(50) NOT NULL DEFAULT 'AMBOS',
    ativo            BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_gf_tenant ON geofences (tenant_id);
CREATE INDEX IF NOT EXISTS idx_gf_ativo ON geofences (ativo);

-- ---------------------------------------------------------------------------
-- TABELA: veiculo_geofence
-- N:N — quais geofences monitoram quais veículos
-- ---------------------------------------------------------------------------
CREATE TABLE veiculo_geofence (
    veiculo_id   BIGINT  NOT NULL,
    geofence_id  BIGINT  NOT NULL,
    ativo        BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (veiculo_id, geofence_id),
 CONSTRAINT fk_vgf_veiculo FOREIGN KEY (veiculo_id) REFERENCES veiculos(id) ON DELETE CASCADE,
 CONSTRAINT fk_vgf_geofence FOREIGN KEY (geofence_id) REFERENCES geofences(id) ON DELETE CASCADE
);

-- ---------------------------------------------------------------------------
-- TABELA: clientes_frete
-- Embarcadores / clientes das transportadoras
-- ---------------------------------------------------------------------------
CREATE TABLE clientes_frete (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id      BIGINT  NOT NULL,
    nome           VARCHAR(255) NOT NULL,
    cnpj           VARCHAR(20),
    telefone       VARCHAR(20),
    email          VARCHAR(255),
    endereco       VARCHAR(500),
    contato_nome   VARCHAR(100),
    ativo          BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_cf_tenant ON clientes_frete (tenant_id);
CREATE INDEX IF NOT EXISTS idx_cf_cnpj ON clientes_frete (cnpj);

-- ---------------------------------------------------------------------------
-- TABELA: cargas
-- Cargas associadas às viagens
-- ---------------------------------------------------------------------------
CREATE TABLE cargas (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid              CHAR(36) NOT NULL UNIQUE DEFAULT (gen_random_uuid()::text),
    tenant_id         BIGINT  NOT NULL,
    cliente_id        BIGINT ,
    descricao         VARCHAR(255) NOT NULL,
    tipo_carga        VARCHAR(50) NOT NULL DEFAULT 'GERAL',
    peso_kg           DOUBLE PRECISION NOT NULL,
    volume_m3         DOUBLE PRECISION,
    valor_declarado   DECIMAL(15,2),
    temp_min_c        DOUBLE PRECISION,
    temp_max_c        DOUBLE PRECISION,
    nfe_chave         VARCHAR(50),
    cte_chave         VARCHAR(50),
    mdfe_chave        VARCHAR(50),
    status            VARCHAR(50) NOT NULL DEFAULT 'PENDENTE',
    criado_em         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT fk_carga_cliente FOREIGN KEY (cliente_id) REFERENCES clientes_frete(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_carga_tenant ON cargas (tenant_id);
CREATE INDEX IF NOT EXISTS idx_carga_cliente ON cargas (cliente_id);
CREATE INDEX IF NOT EXISTS idx_carga_status ON cargas (status);
