-- =============================================================================
-- ROUTE SERVICE — route_db
-- Responsável: Rotas, viagens, desvios, geocoding cache, OSRM integração
-- Porta: 8083
-- =============================================================================

CREATE SCHEMA IF NOT EXISTS route_db;
SET search_path TO route_db, public;
-- ---------------------------------------------------------------------------
-- TABELA: rotas
-- Rota planejada com dados OSRM, pontos de parada e configurações de desvio
-- ---------------------------------------------------------------------------
CREATE TABLE rotas (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                  CHAR(36) NOT NULL UNIQUE DEFAULT (gen_random_uuid()::text),
    tenant_id             BIGINT  NOT NULL,
    nome                  VARCHAR(255) NOT NULL,

    -- Origem
    origem_nome           VARCHAR(255) NOT NULL,
    origem_latitude       DOUBLE PRECISION NOT NULL,
    origem_longitude      DOUBLE PRECISION NOT NULL,
    origem_endereco       VARCHAR(500),

    -- Destino
    destino_nome          VARCHAR(255) NOT NULL,
    destino_latitude      DOUBLE PRECISION NOT NULL,
    destino_longitude     DOUBLE PRECISION NOT NULL,
    destino_endereco      VARCHAR(500),

    -- Dados calculados pelo OSRM
    distancia_km          DOUBLE PRECISION,
    tempo_estimado_min    INT,
    polyline_encoded      TEXT,
    rota_geojson          JSON,
    pontos_snap           JSON,

    -- Paradas intermediárias
    paradas               JSON,
    sequencia_otimizada   JSON,

    -- Custo estimado
    custo_pedagio_est     DECIMAL(10,2),
    custo_combustivel_est DECIMAL(10,2),

    -- Configurações de desvio
    tolerancia_desvio_m   DOUBLE PRECISION NOT NULL DEFAULT 100.0,
    threshold_alerta_m    DOUBLE PRECISION NOT NULL DEFAULT 50.0,

    -- Status e vínculos
    status                VARCHAR(50) NOT NULL DEFAULT 'PLANEJADA',
    veiculo_uuid          CHAR(36),
    motorista_uuid        CHAR(36),
    carga_uuid            CHAR(36),

    -- Datas
    data_inicio_plan      TIMESTAMP,
    data_fim_plan         TIMESTAMP,
    data_inicio_real      TIMESTAMP,
    data_fim_real         TIMESTAMP,

    -- Conformidade
    mdfe_chave            VARCHAR(50),
    ciot_codigo           VARCHAR(30),

    -- Flags
    ativa                 BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP

);
CREATE INDEX IF NOT EXISTS idx_rota_tenant ON rotas (tenant_id);
CREATE INDEX IF NOT EXISTS idx_rota_status ON rotas (status);
CREATE INDEX IF NOT EXISTS idx_rota_veiculo ON rotas (veiculo_uuid);
CREATE INDEX IF NOT EXISTS idx_rota_ativa ON rotas (ativa);
CREATE INDEX IF NOT EXISTS idx_rota_datas ON rotas (data_inicio_plan, data_fim_plan);

-- ---------------------------------------------------------------------------
-- TABELA: viagens
-- Execução real de uma rota (pode haver múltiplas tentativas por rota)
-- ---------------------------------------------------------------------------
CREATE TABLE viagens (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                   CHAR(36) NOT NULL UNIQUE DEFAULT (gen_random_uuid()::text),
    tenant_id              BIGINT  NOT NULL,
    rota_id                BIGINT ,
    veiculo_uuid           CHAR(36) NOT NULL,
    motorista_uuid         CHAR(36),
    carga_uuid             CHAR(36),

    -- Datas
    data_saida_plan        TIMESTAMP,
    data_saida_real        TIMESTAMP,
    data_chegada_plan      TIMESTAMP,
    data_chegada_real      TIMESTAMP,
    eta_atual              TIMESTAMP,

    -- Distância e consumo reais
    distancia_real_km      DOUBLE PRECISION NOT NULL DEFAULT 0,
    consumo_real_l         DOUBLE PRECISION NOT NULL DEFAULT 0,
    km_fora_rota           DOUBLE PRECISION NOT NULL DEFAULT 0,

    -- Status
    status                 VARCHAR(50) NOT NULL DEFAULT 'PLANEJADA',
    motivo_cancelamento    TEXT,

    -- Resumo de ocorrências
    total_desvios          INT NOT NULL DEFAULT 0,
    total_alertas          INT NOT NULL DEFAULT 0,
    total_paradas          INT NOT NULL DEFAULT 0,
    tempo_ocioso_min       INT NOT NULL DEFAULT 0,

    -- Score da viagem
    score_viagem           INT NOT NULL DEFAULT 1000,

    criado_em              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

 CONSTRAINT fk_viagem_rota FOREIGN KEY (rota_id) REFERENCES rotas(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_viagem_tenant ON viagens (tenant_id);
CREATE INDEX IF NOT EXISTS idx_viagem_rota ON viagens (rota_id);
CREATE INDEX IF NOT EXISTS idx_viagem_veiculo ON viagens (veiculo_uuid);
CREATE INDEX IF NOT EXISTS idx_viagem_motorista ON viagens (motorista_uuid);
CREATE INDEX IF NOT EXISTS idx_viagem_status ON viagens (status);
CREATE INDEX IF NOT EXISTS idx_viagem_datas ON viagens (data_saida_real, data_chegada_real);

-- ---------------------------------------------------------------------------
-- TABELA: desvios_rota
-- Registro de cada desvio detectado durante uma viagem
-- ---------------------------------------------------------------------------
CREATE TABLE desvios_rota (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id          BIGINT  NOT NULL,
    viagem_id          BIGINT  NOT NULL,
    rota_id            BIGINT  NOT NULL,
    veiculo_uuid       CHAR(36) NOT NULL,

    latitude_desvio    DOUBLE PRECISION NOT NULL,
    longitude_desvio   DOUBLE PRECISION NOT NULL,
    distancia_metros   DOUBLE PRECISION NOT NULL,
    velocidade_kmh     DOUBLE PRECISION,

    -- Ponto mais próximo na rota planejada
    lat_ponto_mais_proximo  DOUBLE PRECISION,
    lng_ponto_mais_proximo  DOUBLE PRECISION,

    data_hora_desvio   TIMESTAMP NOT NULL,
    data_hora_retorno  TIMESTAMP,
    duracao_min        INT,
    km_extras          DOUBLE PRECISION NOT NULL DEFAULT 0,

    alerta_enviado     BOOLEAN NOT NULL DEFAULT FALSE,
    resolvido          BOOLEAN NOT NULL DEFAULT FALSE,
    motivo             VARCHAR(255),

    criado_em          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

 CONSTRAINT fk_desvio_viagem FOREIGN KEY (viagem_id) REFERENCES viagens(id) ON DELETE CASCADE,
 CONSTRAINT fk_desvio_rota FOREIGN KEY (rota_id) REFERENCES rotas(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_desvio_viagem ON desvios_rota (viagem_id);
CREATE INDEX IF NOT EXISTS idx_desvio_rota ON desvios_rota (rota_id);
CREATE INDEX IF NOT EXISTS idx_desvio_data ON desvios_rota (data_hora_desvio);
CREATE INDEX IF NOT EXISTS idx_desvio_resolv ON desvios_rota (resolvido);

-- ---------------------------------------------------------------------------
-- TABELA: pontos_entrega
-- Registro de cada ponto de parada/entrega realizado na viagem
-- ---------------------------------------------------------------------------
CREATE TABLE pontos_entrega (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT  NOT NULL,
    viagem_id        BIGINT  NOT NULL,
    sequencia        INT NOT NULL,
    nome             VARCHAR(255),
    latitude         DOUBLE PRECISION NOT NULL,
    longitude        DOUBLE PRECISION NOT NULL,
    eta_plan         TIMESTAMP,
    chegada_real     TIMESTAMP,
    saida_real       TIMESTAMP,
    status           VARCHAR(50) NOT NULL DEFAULT 'PENDENTE',
    assinatura_path  VARCHAR(500),
    foto_entrega_path VARCHAR(500),
    observacoes      TEXT,
    criado_em        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT fk_pe_viagem FOREIGN KEY (viagem_id) REFERENCES viagens(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_pe_viagem ON pontos_entrega (viagem_id);
CREATE INDEX IF NOT EXISTS idx_pe_status ON pontos_entrega (status);

-- ---------------------------------------------------------------------------
-- TABELA: osrm_route_cache
-- Cache de rotas calculadas pelo OSRM para evitar recalcular rotas iguais
-- Complementa o cache Redis (persiste rotas para análise e auditoria)
-- ---------------------------------------------------------------------------
CREATE TABLE osrm_route_cache (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cache_key       VARCHAR(64) NOT NULL UNIQUE,
    perfil          VARCHAR(50) NOT NULL DEFAULT 'CAMINHAO',
    lat_origem      DOUBLE PRECISION NOT NULL,
    lng_origem      DOUBLE PRECISION NOT NULL,
    lat_destino     DOUBLE PRECISION NOT NULL,
    lng_destino     DOUBLE PRECISION NOT NULL,
    distancia_km    DOUBLE PRECISION NOT NULL,
    duracao_min     INT NOT NULL,
    polyline        TEXT,
    geojson         JSON,
    hits            INT NOT NULL DEFAULT 1,
    criado_em       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expira_em       TIMESTAMP NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_osrm_cache_key ON osrm_route_cache (cache_key);
CREATE INDEX IF NOT EXISTS idx_osrm_expira ON osrm_route_cache (expira_em);

-- ---------------------------------------------------------------------------
-- TABELA: geocoding_cache
-- Cache de reverse geocoding para evitar chamadas repetidas a APIs externas
-- ---------------------------------------------------------------------------
CREATE TABLE geocoding_cache (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat_arred        DECIMAL(7,4) NOT NULL,
    lng_arred        DECIMAL(7,4) NOT NULL,
    pais            VARCHAR(100),
    estado          VARCHAR(100),
    cidade          VARCHAR(200),
    bairro          VARCHAR(200),
    logradouro      VARCHAR(300),
    nome_local      VARCHAR(255),
    tipo_local      VARCHAR(50),
    is_urbano       BOOLEAN,
    precisao_metros INT,
    consulta_em     TIMESTAMP NOT NULL,
    expira_em       TIMESTAMP NOT NULL,
    CONSTRAINT uk_geocoding_coords UNIQUE (lat_arred, lng_arred)
);
CREATE INDEX IF NOT EXISTS idx_geocoding_expira ON geocoding_cache (expira_em);

-- ---------------------------------------------------------------------------
-- TABELA: historico_posicao_rota
-- Snapshot diário/semanal da trajetória real vs planejada (para relatórios)
-- Dados em tempo real ficam no TimescaleDB do integration-engine-telemetry-service
-- ---------------------------------------------------------------------------
CREATE TABLE historico_posicao_rota (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT  NOT NULL,
    viagem_id   BIGINT  NOT NULL,
    periodo     TIMESTAMP NOT NULL,
    trajeto     JSON NOT NULL,
    criado_em   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT fk_hpr_viagem FOREIGN KEY (viagem_id) REFERENCES viagens(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_hpr_viagem ON historico_posicao_rota (viagem_id);
CREATE INDEX IF NOT EXISTS idx_hpr_periodo ON historico_posicao_rota (periodo);
