-- =============================================================================
-- ALERT SERVICE — alert_db
-- Responsável: Motor de regras, alertas em tempo real, notificações
-- Porta: 8086
-- =============================================================================

CREATE SCHEMA IF NOT EXISTS alert_db;
SET search_path TO alert_db, public;
-- ---------------------------------------------------------------------------
-- TABELA: regras_alerta
-- Motor de regras configurável por tenant (no-code para gestores)
-- ---------------------------------------------------------------------------
CREATE TABLE regras_alerta (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid             CHAR(36) NOT NULL UNIQUE DEFAULT (gen_random_uuid()::text),
    tenant_id        BIGINT  NOT NULL,
    nome             VARCHAR(255) NOT NULL,
    descricao        TEXT,
    -- Trigger
    tipo_evento      VARCHAR(50) NOT NULL,
    condicoes        JSON NOT NULL,
    logica           VARCHAR(50) NOT NULL DEFAULT 'AND',
    duracao_seg      INT NOT NULL DEFAULT 0,
    -- Ação
    severidade       VARCHAR(50) NOT NULL DEFAULT 'MEDIO',
    acoes            JSON NOT NULL,
    cooldown_min     INT NOT NULL DEFAULT 15,
    -- Escopo
    aplica_todos     BOOLEAN NOT NULL DEFAULT TRUE,
    veiculos_uuid    JSON,
    tipo_carga       JSON,
    -- Controle
    ativo            BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_regra_tenant ON regras_alerta (tenant_id);
CREATE INDEX IF NOT EXISTS idx_regra_ativo ON regras_alerta (ativo);
CREATE INDEX IF NOT EXISTS idx_regra_tipo ON regras_alerta (tipo_evento);

-- ---------------------------------------------------------------------------
-- TABELA: alertas
-- Alertas gerados — cada disparo do motor de regras cria um registro
-- ---------------------------------------------------------------------------
CREATE TABLE alertas (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid             CHAR(36) NOT NULL UNIQUE DEFAULT (gen_random_uuid()::text),
    tenant_id        BIGINT  NOT NULL,
    regra_id         BIGINT ,
    veiculo_uuid     CHAR(36) NOT NULL,
    motorista_uuid   CHAR(36),
    viagem_uuid      CHAR(36),

    tipo             VARCHAR(80) NOT NULL,
    severidade       VARCHAR(50) NOT NULL DEFAULT 'MEDIO',
    mensagem         TEXT NOT NULL,
    dados_contexto   JSON,

    -- Localização no momento do alerta
    latitude         DOUBLE PRECISION,
    longitude        DOUBLE PRECISION,
    velocidade_kmh   DOUBLE PRECISION,
    odometro_km      DOUBLE PRECISION,

    data_hora        TIMESTAMP NOT NULL,

    -- Gestão
    lido             BOOLEAN NOT NULL DEFAULT FALSE,
    lido_por         VARCHAR(255),
    data_hora_leitura TIMESTAMP,
    resolvido        BOOLEAN NOT NULL DEFAULT FALSE,
    resolvido_por    VARCHAR(255),
    data_hora_resolucao TIMESTAMP,
    observacao_resolucao TEXT,

    criado_em        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

 CONSTRAINT fk_alerta_regra FOREIGN KEY (regra_id) REFERENCES regras_alerta(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_alerta_tenant ON alertas (tenant_id);
CREATE INDEX IF NOT EXISTS idx_alerta_veiculo ON alertas (veiculo_uuid);
CREATE INDEX IF NOT EXISTS idx_alerta_tipo ON alertas (tipo);
CREATE INDEX IF NOT EXISTS idx_alerta_sev ON alertas (severidade);
CREATE INDEX IF NOT EXISTS idx_alerta_data ON alertas (data_hora);
CREATE INDEX IF NOT EXISTS idx_alerta_lido ON alertas (lido);
CREATE INDEX IF NOT EXISTS idx_alerta_resolv ON alertas (resolvido);

-- ---------------------------------------------------------------------------
-- TABELA: notificacoes
-- Fila de notificações enviadas para cada canal
-- ---------------------------------------------------------------------------
CREATE TABLE notificacoes (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT  NOT NULL,
    alerta_id        BIGINT ,
    canal            VARCHAR(50) NOT NULL,
    destinatario     VARCHAR(255) NOT NULL,
    assunto          VARCHAR(255),
    corpo            TEXT NOT NULL,
    status           VARCHAR(50) NOT NULL DEFAULT 'PENDENTE',
    tentativas       SMALLINT  NOT NULL DEFAULT 0,
    proximo_retry    TIMESTAMP,
    id_externo       VARCHAR(100),
    erro_detalhe     TEXT,
    enviado_em       TIMESTAMP,
    criado_em        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT fk_notif_alerta FOREIGN KEY (alerta_id) REFERENCES alertas(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_notif_tenant ON notificacoes (tenant_id);
CREATE INDEX IF NOT EXISTS idx_notif_alerta ON notificacoes (alerta_id);
CREATE INDEX IF NOT EXISTS idx_notif_status ON notificacoes (status);
CREATE INDEX IF NOT EXISTS idx_notif_retry ON notificacoes (proximo_retry, status);

-- ---------------------------------------------------------------------------
-- TABELA: webhook_deliveries
-- Histórico de entregas de webhooks para integrações externas
-- ---------------------------------------------------------------------------
CREATE TABLE webhook_deliveries (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT  NOT NULL,
    alerta_uuid     CHAR(36),
    url_destino     VARCHAR(500) NOT NULL,
    payload         JSON NOT NULL,
    http_status     SMALLINT,
    resposta        TEXT,
    tentativa       SMALLINT  NOT NULL DEFAULT 1,
    sucesso         BOOLEAN NOT NULL DEFAULT FALSE,
    enviado_em      TIMESTAMP NOT NULL,
    criado_em       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_whd_tenant ON webhook_deliveries (tenant_id);
CREATE INDEX IF NOT EXISTS idx_whd_sucesso ON webhook_deliveries (sucesso);
CREATE INDEX IF NOT EXISTS idx_whd_enviado ON webhook_deliveries (enviado_em);


-- =============================================================================
-- MAINTENANCE SERVICE — maintenance_db
-- Responsável: Manutenções preventivas/corretivas, manutenção preditiva IA, RUL
-- Porta: integrado ao vehicle-service ou separado
-- =============================================================================

CREATE SCHEMA IF NOT EXISTS maintenance_db;
SET search_path TO maintenance_db, public;
-- ---------------------------------------------------------------------------
-- TABELA: manutencoes
-- Registro de manutenções realizadas e agendadas
-- ---------------------------------------------------------------------------
CREATE TABLE manutencoes (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid             CHAR(36) NOT NULL UNIQUE DEFAULT (gen_random_uuid()::text),
    tenant_id        BIGINT  NOT NULL,
    veiculo_uuid     CHAR(36) NOT NULL,
    tipo             VARCHAR(50) NOT NULL DEFAULT 'PREVENTIVA',
    categoria        VARCHAR(100),
    descricao        VARCHAR(255) NOT NULL,
    observacoes      TEXT,
    status           VARCHAR(50) NOT NULL DEFAULT 'AGENDADA',
    data_agendada    DATE,
    data_realizada   DATE,
    km_agendado      DOUBLE PRECISION,
    km_realizado     DOUBLE PRECISION,
    horas_agendado   DOUBLE PRECISION,
    custo_pecas      DECIMAL(10,2) NOT NULL DEFAULT 0,
    custo_mao_obra   DECIMAL(10,2) NOT NULL DEFAULT 0,
    custo_total      DECIMAL(10,2) NOT NULL DEFAULT 0,
    fornecedor       VARCHAR(255),
    nota_fiscal      VARCHAR(50),
    alerta_enviado   BOOLEAN NOT NULL DEFAULT FALSE,
    -- Origem preditiva
    originada_ml     BOOLEAN NOT NULL DEFAULT FALSE,
    modelo_ml_versao VARCHAR(30),
    confianca_ml     DOUBLE PRECISION,
    criado_em        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_man_tenant ON manutencoes (tenant_id);
CREATE INDEX IF NOT EXISTS idx_man_veiculo ON manutencoes (veiculo_uuid);
CREATE INDEX IF NOT EXISTS idx_man_status ON manutencoes (status);
CREATE INDEX IF NOT EXISTS idx_man_data ON manutencoes (data_agendada);
CREATE INDEX IF NOT EXISTS idx_man_tipo ON manutencoes (tipo);

-- ---------------------------------------------------------------------------
-- TABELA: componentes
-- Componentes monitorados individualmente por veículo (para RUL)
-- ---------------------------------------------------------------------------
CREATE TABLE componentes (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id         BIGINT  NOT NULL,
    veiculo_uuid      CHAR(36) NOT NULL,
    nome              VARCHAR(100) NOT NULL,
    fabricante        VARCHAR(100),
    modelo_peca       VARCHAR(100),
    numero_serie      VARCHAR(50),
    km_instalado      DOUBLE PRECISION,
    horas_instalado   DOUBLE PRECISION,
    vida_util_km_est  DOUBLE PRECISION NOT NULL DEFAULT 100000,
    -- RUL calculado pelo ML
    rul_km_estimado   DOUBLE PRECISION,
    rul_dias_estimado INT,
    anomaly_score     DOUBLE PRECISION NOT NULL DEFAULT 0,
    status            VARCHAR(50) NOT NULL DEFAULT 'BOM',
    ultimo_modelo_ml  VARCHAR(30),
    ultima_pred_em    TIMESTAMP,
    instalado_em      DATE,
    substituido_em    DATE,
    criado_em         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_comp_veiculo ON componentes (veiculo_uuid);
CREATE INDEX IF NOT EXISTS idx_comp_status ON componentes (status);
CREATE INDEX IF NOT EXISTS idx_comp_rul ON componentes (rul_dias_estimado);

-- ---------------------------------------------------------------------------
-- TABELA: predicoes_ml
-- Histórico de predições de manutenção preditiva geradas pelos modelos IA
-- ---------------------------------------------------------------------------
CREATE TABLE predicoes_ml (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT  NOT NULL,
    veiculo_uuid    CHAR(36) NOT NULL,
    componente_id   BIGINT ,
    modelo          VARCHAR(50) NOT NULL,
    versao_modelo   VARCHAR(30) NOT NULL,
    tipo_predicao   VARCHAR(50) NOT NULL,
    score           DOUBLE PRECISION NOT NULL,
    probabilidade   DOUBLE PRECISION NOT NULL DEFAULT 0,
    rul_km          DOUBLE PRECISION,
    rul_dias        INT,
    features_input  JSON,
    acao_recomendada TEXT,
    acionada        BOOLEAN NOT NULL DEFAULT FALSE,
    manutencao_id   BIGINT ,
    predito_em      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT fk_pred_comp FOREIGN KEY (componente_id) REFERENCES componentes(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_pred_veiculo ON predicoes_ml (veiculo_uuid);
CREATE INDEX IF NOT EXISTS idx_pred_tipo ON predicoes_ml (tipo_predicao);
CREATE INDEX IF NOT EXISTS idx_pred_em ON predicoes_ml (predito_em);

-- ---------------------------------------------------------------------------
-- TABELA: abastecimentos
-- Registro de abastecimentos com detecção de fraude
-- ---------------------------------------------------------------------------
CREATE TABLE abastecimentos (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           BIGINT  NOT NULL,
    veiculo_uuid        CHAR(36) NOT NULL,
    motorista_uuid      CHAR(36),
    viagem_uuid         CHAR(36),
    data_hora           TIMESTAMP NOT NULL,
    posto_nome          VARCHAR(255),
    posto_cnpj          VARCHAR(20),
    latitude            DOUBLE PRECISION,
    longitude           DOUBLE PRECISION,
    litros_declarados   DOUBLE PRECISION NOT NULL,
    litros_sensor       DOUBLE PRECISION,
    tipo_combustivel    VARCHAR(50) NOT NULL DEFAULT 'DIESEL',
    valor_litro         DECIMAL(6,3),
    valor_total         DECIMAL(10,2),
    odometro_km         DOUBLE PRECISION,
    km_desde_ultimo     DOUBLE PRECISION,
    consumo_kmpl        DOUBLE PRECISION,
    cupom_foto_path     VARCHAR(500),
    -- Fraude
    fraude_score        DOUBLE PRECISION NOT NULL DEFAULT 0,
    fraude_tipo         VARCHAR(100),
    alerta_fraude       BOOLEAN NOT NULL DEFAULT FALSE,
    posto_autorizado    BOOLEAN NOT NULL DEFAULT TRUE,
    revisado            BOOLEAN NOT NULL DEFAULT FALSE,
    criado_em           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_abas_tenant ON abastecimentos (tenant_id);
CREATE INDEX IF NOT EXISTS idx_abas_veiculo ON abastecimentos (veiculo_uuid);
CREATE INDEX IF NOT EXISTS idx_abas_data ON abastecimentos (data_hora);
CREATE INDEX IF NOT EXISTS idx_abas_fraude ON abastecimentos (alerta_fraude);


-- =============================================================================
-- BILLING SERVICE — billing_db
-- Responsável: Planos, cobranças, uso, métricas para faturamento
-- Porta: 8089
-- =============================================================================

CREATE SCHEMA IF NOT EXISTS billing_db;
SET search_path TO billing_db, public;
-- ---------------------------------------------------------------------------
-- TABELA: planos
-- Definição dos planos SaaS
-- ---------------------------------------------------------------------------
CREATE TABLE planos (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                VARCHAR(50) NOT NULL UNIQUE,
    preco_veiculo_mes   DECIMAL(8,2) NOT NULL,
    min_veiculos        INT NOT NULL DEFAULT 1,
    max_veiculos        INT,
    features            JSON NOT NULL,
    sla_uptime          DECIMAL(5,2) NOT NULL,
    ativo               BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO planos (nome, preco_veiculo_mes, min_veiculos, max_veiculos, features, sla_uptime) VALUES
    ('STARTER',    49.00,  1,  9,   '{"app_motorista":false,"osrm":false,"ia_preditiva":false,"satelite":false,"api":false}', 99.00),
    ('PRO',        99.00,  10, 49,  '{"app_motorista":true,"osrm":true,"ia_preditiva":false,"satelite":false,"api":false}',   99.50),
    ('ENTERPRISE', 159.00, 50, 499, '{"app_motorista":true,"osrm":true,"ia_preditiva":true,"satelite":"addon","api":true}',   99.90),
    ('CUSTOM',     0.00,   500, NULL,'{"app_motorista":true,"osrm":true,"ia_preditiva":true,"satelite":true,"api":true}',     99.99);

-- ---------------------------------------------------------------------------
-- TABELA: assinaturas
-- Assinatura ativa de cada tenant
-- ---------------------------------------------------------------------------
CREATE TABLE assinaturas (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_uuid         CHAR(36) NOT NULL UNIQUE,
    plano_id            BIGINT  NOT NULL,
    status              VARCHAR(50) NOT NULL DEFAULT 'TRIAL',
    veiculos_contratados INT NOT NULL DEFAULT 1,
    data_inicio         DATE NOT NULL,
    data_fim            DATE,
    trial_expira        DATE,
    -- Gateway de pagamento
    gateway             VARCHAR(50) NOT NULL DEFAULT 'PAGSEGURO',
    customer_id_gw      VARCHAR(100),
    subscription_id_gw  VARCHAR(100),
    -- Desconto
    desconto_pct        DECIMAL(5,2) NOT NULL DEFAULT 0,
    motivo_desconto     VARCHAR(255),
    criado_em           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT fk_assin_plano FOREIGN KEY (plano_id) REFERENCES planos(id)
);
CREATE INDEX IF NOT EXISTS idx_assin_status ON assinaturas (status);

-- ---------------------------------------------------------------------------
-- TABELA: faturas
-- Faturas mensais geradas para cada tenant
-- ---------------------------------------------------------------------------
CREATE TABLE faturas (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                CHAR(36) NOT NULL UNIQUE DEFAULT (gen_random_uuid()::text),
    tenant_uuid         CHAR(36) NOT NULL,
    assinatura_id       BIGINT  NOT NULL,
    periodo_ref         DATE NOT NULL,
    veiculos_faturados  INT NOT NULL,
    preco_unitario      DECIMAL(8,2) NOT NULL,
    subtotal            DECIMAL(12,2) NOT NULL,
    desconto            DECIMAL(12,2) NOT NULL DEFAULT 0,
    total               DECIMAL(12,2) NOT NULL,
    status              VARCHAR(50) NOT NULL DEFAULT 'PENDENTE',
    data_vencimento     DATE NOT NULL,
    data_pagamento      DATE,
    linha_digitavel     VARCHAR(80),
    pix_copia_cola      TEXT,
    invoice_id_gw       VARCHAR(100),
    pdf_path            VARCHAR(500),
    criado_em           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT fk_fatura_assin FOREIGN KEY (assinatura_id) REFERENCES assinaturas(id)
);
CREATE INDEX IF NOT EXISTS idx_fatura_tenant ON faturas (tenant_uuid);
CREATE INDEX IF NOT EXISTS idx_fatura_status ON faturas (status);
CREATE INDEX IF NOT EXISTS idx_fatura_periodo ON faturas (periodo_ref);

-- ---------------------------------------------------------------------------
-- TABELA: uso_mensal
-- Métricas de uso por tenant para billing e análise
-- ---------------------------------------------------------------------------
CREATE TABLE uso_mensal (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_uuid          CHAR(36) NOT NULL,
    periodo              DATE NOT NULL,
    veiculos_ativos      INT NOT NULL DEFAULT 0,
    total_eventos        BIGINT NOT NULL DEFAULT 0,
    total_km             DOUBLE PRECISION NOT NULL DEFAULT 0,
    total_viagens        INT NOT NULL DEFAULT 0,
    total_alertas        INT NOT NULL DEFAULT 0,
    requests_api         BIGINT NOT NULL DEFAULT 0,
    storage_mb           DOUBLE PRECISION NOT NULL DEFAULT 0,
    chamadas_osrm        INT NOT NULL DEFAULT 0,
    chamadas_satelite    INT NOT NULL DEFAULT 0,
    criado_em            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_uso_tenant_periodo UNIQUE (tenant_uuid, periodo)
);
CREATE INDEX IF NOT EXISTS idx_uso_periodo ON uso_mensal (periodo);


-- =============================================================================
-- OTA SERVICE — ota_db
-- Responsável: Firmware, distribuição OTA, rollout canário, audit trail
-- Porta: 8091
-- =============================================================================

CREATE SCHEMA IF NOT EXISTS ota_db;
SET search_path TO ota_db, public;
-- ---------------------------------------------------------------------------
-- TABELA: firmware_versoes
-- Catálogo de versões de firmware dos rastreadores
-- ---------------------------------------------------------------------------
CREATE TABLE firmware_versoes (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    versao           VARCHAR(30) NOT NULL UNIQUE,
    versao_anterior  VARCHAR(30),
    arquivo_path     VARCHAR(500) NOT NULL,
    delta_path       VARCHAR(500),
    tamanho_bytes    BIGINT NOT NULL,
    delta_bytes      BIGINT,
    hash_sha256      VARCHAR(64) NOT NULL,
    hash_delta_sha256 VARCHAR(64),
    assinatura_hsm   TEXT NOT NULL,
    changelog        TEXT,
    tipo             VARCHAR(50) NOT NULL DEFAULT 'PATCH',
    status           VARCHAR(50) NOT NULL DEFAULT 'EM_TESTE',
    modelo_hardware  VARCHAR(50),
    criado_em        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_fw_status ON firmware_versoes (status);
CREATE INDEX IF NOT EXISTS idx_fw_versao ON firmware_versoes (versao);

-- ---------------------------------------------------------------------------
-- TABELA: ota_jobs
-- Jobs de atualização OTA por tenant/versão com estratégia de rollout
-- ---------------------------------------------------------------------------
CREATE TABLE ota_jobs (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid              CHAR(36) NOT NULL UNIQUE DEFAULT (gen_random_uuid()::text),
    tenant_id         BIGINT  NOT NULL,
    firmware_id       BIGINT  NOT NULL,
    estrategia        VARCHAR(50) NOT NULL DEFAULT 'CANARY_1PCT',
    dispositivos_alvo JSON,
    pct_rollout       DECIMAL(5,2) NOT NULL DEFAULT 1.0,
    total_dispositivos INT NOT NULL DEFAULT 0,
    enviados          INT NOT NULL DEFAULT 0,
    sucessos          INT NOT NULL DEFAULT 0,
    falhas            INT NOT NULL DEFAULT 0,
    rollbacks         INT NOT NULL DEFAULT 0,
    status            VARCHAR(50) NOT NULL DEFAULT 'AGENDADO',
    auto_rollback     BOOLEAN NOT NULL DEFAULT TRUE,
    erro_rate_limite  DECIMAL(5,2) NOT NULL DEFAULT 2.0,
    iniciado_em       TIMESTAMP,
    concluido_em      TIMESTAMP,
    criado_por        VARCHAR(255),
    criado_em         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT fk_ota_job_fw FOREIGN KEY (firmware_id) REFERENCES firmware_versoes(id)
);
CREATE INDEX IF NOT EXISTS idx_ota_job_tenant ON ota_jobs (tenant_id);
CREATE INDEX IF NOT EXISTS idx_ota_job_status ON ota_jobs (status);

-- ---------------------------------------------------------------------------
-- TABELA: ota_dispositivos
-- Status de atualização por dispositivo individual
-- ---------------------------------------------------------------------------
CREATE TABLE ota_dispositivos (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id          BIGINT  NOT NULL,
    device_id       VARCHAR(64) NOT NULL,
    veiculo_uuid    CHAR(36),
    tenant_id       BIGINT  NOT NULL,
    versao_atual    VARCHAR(30) NOT NULL,
    versao_alvo     VARCHAR(30) NOT NULL,
    usa_delta       BOOLEAN NOT NULL DEFAULT TRUE,
    status          VARCHAR(50) NOT NULL DEFAULT 'PENDENTE',
    token_unico     VARCHAR(64) NOT NULL UNIQUE,
    tentativas      SMALLINT  NOT NULL DEFAULT 0,
    progresso_pct   SMALLINT  NOT NULL DEFAULT 0,
    erro_detalhe    TEXT,
    iniciado_em     TIMESTAMP,
    concluido_em    TIMESTAMP,
    criado_em       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT fk_ota_disp_job FOREIGN KEY (job_id) REFERENCES ota_jobs(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_ota_disp_job ON ota_dispositivos (job_id);
CREATE INDEX IF NOT EXISTS idx_ota_disp_device ON ota_dispositivos (device_id);
CREATE INDEX IF NOT EXISTS idx_ota_disp_status ON ota_dispositivos (status);

-- ---------------------------------------------------------------------------
-- TABELA: ota_audit_log
-- Log imutável de todas as atualizações OTA
-- ---------------------------------------------------------------------------
CREATE TABLE ota_audit_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id       VARCHAR(64) NOT NULL,
    job_id          BIGINT ,
    versao_anterior VARCHAR(30),
    versao_nova     VARCHAR(30),
    evento          VARCHAR(50) NOT NULL,
    detalhes        JSON,
    sucesso         BOOLEAN NOT NULL,
    registrado_em   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_ota_audit_device ON ota_audit_log (device_id);
CREATE INDEX IF NOT EXISTS idx_ota_audit_job ON ota_audit_log (job_id);
CREATE INDEX IF NOT EXISTS idx_ota_audit_em ON ota_audit_log (registrado_em);
