CREATE TABLE IF NOT EXISTS tenants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_razao_social VARCHAR(255) NOT NULL,
    cnpj VARCHAR(14) NOT NULL,
    plano VARCHAR(20) NOT NULL DEFAULT 'STARTER',
    status VARCHAR(20) NOT NULL DEFAULT 'TRIAL',
    trial_inicio DATE NOT NULL,
    trial_expira_em DATE NOT NULL,
    dados_preservados_ate DATE,
    email VARCHAR(200),
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_tenants_cnpj UNIQUE (cnpj)
);

CREATE INDEX IF NOT EXISTS idx_tenant_status ON tenants (status);

ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS tenant_id BIGINT;
CREATE INDEX IF NOT EXISTS idx_usr_tenant ON usuarios (tenant_id);
