CREATE TABLE IF NOT EXISTS escalas_motorista (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    motorista_id BIGINT NOT NULL,
    veiculo_id BIGINT NOT NULL,
    rota_id BIGINT,
    data_inicio_turno TIMESTAMP NOT NULL,
    data_fim_turno TIMESTAMP NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PLANEJADA',
    confirmado_motorista BOOLEAN NOT NULL DEFAULT FALSE,
    motivo_cancelamento TEXT,
    criado_por VARCHAR(36)
);

CREATE INDEX IF NOT EXISTS idx_esc_motorista_inicio ON escalas_motorista (motorista_id, data_inicio_turno);
CREATE INDEX IF NOT EXISTS idx_esc_veiculo_inicio ON escalas_motorista (veiculo_id, data_inicio_turno);

CREATE TABLE IF NOT EXISTS abastecimentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    veiculo_id BIGINT NOT NULL,
    motorista_id BIGINT,
    data_hora TIMESTAMP NOT NULL,
    litros DOUBLE PRECISION NOT NULL,
    valor_total DOUBLE PRECISION NOT NULL,
    odometro DOUBLE PRECISION,
    posto_cnpj VARCHAR(14),
    tipo_combustivel VARCHAR(30),
    tipo_origem VARCHAR(20) NOT NULL,
    litros_sensor DOUBLE PRECISION,
    fraude_score INT NOT NULL DEFAULT 0,
    posto_autorizado BOOLEAN,
    status_conciliacao VARCHAR(20) NOT NULL DEFAULT 'PENDENTE'
);

CREATE INDEX IF NOT EXISTS idx_aba_tenant_data ON abastecimentos (tenant_id, data_hora);
CREATE INDEX IF NOT EXISTS idx_aba_veiculo ON abastecimentos (veiculo_id);

CREATE TABLE IF NOT EXISTS ota_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    device_id VARCHAR(64) NOT NULL,
    versao_alvo VARCHAR(30) NOT NULL,
    sha256 VARCHAR(64) NOT NULL,
    assinatura_hsm TEXT NOT NULL,
    fase VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    token_consumido BOOLEAN NOT NULL DEFAULT FALSE,
    erro TEXT,
    criado_em TIMESTAMP NOT NULL,
    atualizado_em TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_ota_tenant_status ON ota_jobs (tenant_id, status);
CREATE INDEX IF NOT EXISTS idx_ota_device ON ota_jobs (device_id);
ALTER TABLE manutencoes ADD COLUMN IF NOT EXISTS custo_pecas DOUBLE PRECISION NULL;
ALTER TABLE manutencoes ADD COLUMN IF NOT EXISTS custo_mao_obra DOUBLE PRECISION NULL;
ALTER TABLE manutencoes ADD COLUMN IF NOT EXISTS nota_fiscal_path VARCHAR(500) NULL;
ALTER TABLE manutencoes ADD COLUMN IF NOT EXISTS data_agendada DATE NULL;
ALTER TABLE manutencoes ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'AGENDADA';
ALTER TABLE manutencoes ADD COLUMN IF NOT EXISTS anomaly_score DOUBLE PRECISION NULL;
ALTER TABLE manutencoes ADD COLUMN IF NOT EXISTS rul_dias_estimado INT NULL;
ALTER TABLE manutencoes ADD COLUMN IF NOT EXISTS probabilidade_falha DOUBLE PRECISION NULL;
