-- Estruturas presentes no modelo JPA que ainda não eram gerenciadas pelo Flyway.

ALTER TABLE desvios_rota ADD COLUMN IF NOT EXISTS aprovado_gestor BOOLEAN;
ALTER TABLE desvios_rota ADD COLUMN IF NOT EXISTS data_aprovacao_gestor TIMESTAMP;
ALTER TABLE desvios_rota ADD COLUMN IF NOT EXISTS gestor_id BIGINT;
ALTER TABLE desvios_rota ADD COLUMN IF NOT EXISTS justificativa_gestor VARCHAR(500);
ALTER TABLE desvios_rota ADD COLUMN IF NOT EXISTS tipo_via VARCHAR(30);

CREATE INDEX IF NOT EXISTS idx_desvio_tipo_via ON desvios_rota (tipo_via);

ALTER TABLE posicao_atual ADD COLUMN IF NOT EXISTS zona_atual VARCHAR(255);
ALTER TABLE telemetria ADD COLUMN IF NOT EXISTS uso_celular BOOLEAN;
ALTER TABLE telemetria ALTER COLUMN qualidade_dados TYPE INTEGER;

-- O tenant de viagens legadas é inferido somente a partir de relacionamentos
-- que já pertencem a um tenant. A migration falha em vez de atribuir dados ao
-- tenant errado quando não existe informação suficiente.
ALTER TABLE viagens ADD COLUMN IF NOT EXISTS tenant_id BIGINT;

UPDATE viagens viagem
SET tenant_id = COALESCE(
    (SELECT veiculo.tenant_id FROM veiculos veiculo WHERE veiculo.id = viagem.veiculo_id),
    (SELECT motorista.tenant_id FROM motoristas motorista WHERE motorista.id = viagem.motorista_id)
)
WHERE viagem.tenant_id IS NULL;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM viagens WHERE tenant_id IS NULL) THEN
        RAISE EXCEPTION
            'Não foi possível determinar o tenant de todas as viagens legadas';
    END IF;
END $$;

ALTER TABLE viagens ALTER COLUMN tenant_id SET NOT NULL;
CREATE INDEX IF NOT EXISTS idx_via_tenant ON viagens (tenant_id);

CREATE TABLE IF NOT EXISTS historico_eta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    viagem_id BIGINT NOT NULL,
    veiculo_id BIGINT NOT NULL,
    latitude_atual DOUBLE PRECISION,
    longitude_atual DOUBLE PRECISION,
    minutos_restantes DOUBLE PRECISION,
    distancia_restante_km DOUBLE PRECISION,
    eta_previsto TIMESTAMP,
    eta_calculado TIMESTAMP,
    atraso_minutos BIGINT,
    status_eta VARCHAR(20),
    motivo_indeterminado VARCHAR(255),
    velocidade_atual_kmh DOUBLE PRECISION,
    tempo_parado_minutos INTEGER,
    parada_prevista BOOLEAN NOT NULL DEFAULT FALSE,
    data_calculo TIMESTAMP NOT NULL,
    notificacao_enviada_30min BOOLEAN NOT NULL DEFAULT FALSE,
    notificacao_enviada_60min BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_eta_viagem FOREIGN KEY (viagem_id) REFERENCES viagens(id) ON DELETE CASCADE,
    CONSTRAINT fk_eta_veiculo FOREIGN KEY (veiculo_id) REFERENCES veiculos(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_eta_viagem ON historico_eta (viagem_id);
CREATE INDEX IF NOT EXISTS idx_eta_data ON historico_eta (data_calculo);
CREATE INDEX IF NOT EXISTS idx_eta_veiculo ON historico_eta (veiculo_id);

CREATE TABLE IF NOT EXISTS pontos_entrega (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    viagem_id BIGINT NOT NULL,
    rota_id BIGINT NOT NULL,
    ordem INTEGER NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDENTE',
    nome_destinatario VARCHAR(255),
    endereco VARCHAR(500),
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    raio_metros INTEGER NOT NULL DEFAULT 50,
    assinatura_path VARCHAR(500),
    foto_entrega_path VARCHAR(500),
    ocorrencia VARCHAR(1000),
    data_chegada TIMESTAMP,
    data_entrega TIMESTAMP,
    tempo_permanencia_min INTEGER,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP,
    CONSTRAINT ck_pe_tipo CHECK (
        tipo IN ('COLETA', 'ENTREGA', 'PARADA', 'ABASTECIMENTO', 'PERNOITE')
    ),
    CONSTRAINT ck_pe_status CHECK (
        status IN ('PENDENTE', 'CHEGOU', 'ENTREGUE', 'FALHOU', 'PULADO')
    ),
    CONSTRAINT fk_pe_viagem FOREIGN KEY (viagem_id) REFERENCES viagens(id) ON DELETE CASCADE,
    CONSTRAINT fk_pe_rota FOREIGN KEY (rota_id) REFERENCES rotas(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_pe_viagem ON pontos_entrega (viagem_id);
CREATE INDEX IF NOT EXISTS idx_pe_rota ON pontos_entrega (rota_id);
CREATE INDEX IF NOT EXISTS idx_pe_status ON pontos_entrega (status);
CREATE INDEX IF NOT EXISTS idx_pe_tipo ON pontos_entrega (tipo);
CREATE INDEX IF NOT EXISTS idx_pe_ordem ON pontos_entrega (ordem);

CREATE TABLE IF NOT EXISTS score_viagem (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    viagem_id BIGINT NOT NULL,
    motorista_id BIGINT NOT NULL,
    veiculo_id BIGINT NOT NULL,
    score_inicial INTEGER NOT NULL DEFAULT 1000,
    score_final INTEGER NOT NULL DEFAULT 1000,
    penalidade_frenagem_brusca INTEGER DEFAULT 0,
    penalidade_excesso_velocidade INTEGER DEFAULT 0,
    penalidade_desvio_nao_justificado INTEGER DEFAULT 0,
    penalidade_uso_celular INTEGER DEFAULT 0,
    penalidade_entrega_fora_janela INTEGER DEFAULT 0,
    quantidade_frenagem_brusca INTEGER DEFAULT 0,
    quantidade_excesso_velocidade INTEGER DEFAULT 0,
    quantidade_desvio_nao_justificado INTEGER DEFAULT 0,
    quantidade_uso_celular INTEGER DEFAULT 0,
    quantidade_entrega_fora_janela INTEGER DEFAULT 0,
    notificacao_gestor_enviada BOOLEAN DEFAULT FALSE,
    score_classificacao VARCHAR(20),
    observacoes VARCHAR(500),
    data_calculo TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_score_viagem FOREIGN KEY (viagem_id) REFERENCES viagens(id) ON DELETE CASCADE,
    CONSTRAINT fk_score_motorista FOREIGN KEY (motorista_id) REFERENCES motoristas(id) ON DELETE CASCADE,
    CONSTRAINT fk_score_veiculo FOREIGN KEY (veiculo_id) REFERENCES veiculos(id) ON DELETE CASCADE,
    CONSTRAINT ck_score_inicial CHECK (score_inicial BETWEEN 0 AND 1000),
    CONSTRAINT ck_score_final CHECK (score_final BETWEEN 0 AND 1000)
);

CREATE INDEX IF NOT EXISTS idx_score_viagem ON score_viagem (viagem_id);
CREATE INDEX IF NOT EXISTS idx_score_motorista ON score_viagem (motorista_id);
CREATE INDEX IF NOT EXISTS idx_score_data ON score_viagem (data_calculo);
