-- =============================================================================
-- V1__create_telemetria_schema.sql
-- TELEMETRY SERVICE — telemetry_db
-- Script completo para PostgreSQL 16
-- Versão: 1.0
-- =============================================================================

-- Cria o banco de dados se não existir
-- O banco é criado pela infraestrutura; a migration atua na conexão atual.
-- =============================================================================
-- SEÇÃO 1 — CADASTROS BASE (caches locais)
-- =============================================================================

CREATE TABLE IF NOT EXISTS veiculos_cache (
    id                  BIGINT  NOT NULL PRIMARY KEY,
    uuid                VARCHAR(36) NOT NULL UNIQUE,
    tenant_id           BIGINT  NOT NULL,
    placa               VARCHAR(10) NOT NULL,
    modelo              VARCHAR(255) NOT NULL,
    marca               VARCHAR(100),
    tipo_veiculo        VARCHAR(50) NOT NULL DEFAULT 'CAMINHAO_PESADO',
    consumo_medio       DOUBLE PRECISION,
    capacidade_carga_kg DOUBLE PRECISION,
    device_id           VARCHAR(64),
    device_imei         VARCHAR(20),
    pbt_kg              DOUBLE PRECISION,
    ativo               BOOLEAN NOT NULL DEFAULT TRUE,
    sincronizado_em     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_vc_tenant ON veiculos_cache (tenant_id);
CREATE INDEX IF NOT EXISTS idx_vc_device ON veiculos_cache (device_id);
CREATE INDEX IF NOT EXISTS idx_vc_placa ON veiculos_cache (placa);

CREATE TABLE IF NOT EXISTS motoristas_cache (
    id              BIGINT  NOT NULL PRIMARY KEY,
    uuid            VARCHAR(36) NOT NULL UNIQUE,
    tenant_id       BIGINT  NOT NULL,
    nome            VARCHAR(255) NOT NULL,
    cpf             VARCHAR(14) NOT NULL,
    cnh             VARCHAR(50) NOT NULL,
    categoria_cnh   VARCHAR(10) NOT NULL,
    ativo           BOOLEAN NOT NULL DEFAULT TRUE,
    sincronizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_mc_tenant ON motoristas_cache (tenant_id);
CREATE INDEX IF NOT EXISTS idx_mc_cpf ON motoristas_cache (cpf);

-- =============================================================================
-- SEÇÃO 1.5 — CLIENTES E CARGAS
-- =============================================================================

CREATE TABLE IF NOT EXISTS clientes (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_razao_social   VARCHAR(255) NOT NULL,
    cnpj                VARCHAR(18) NOT NULL UNIQUE,
    email               VARCHAR(200),
    telefone            VARCHAR(20),
    endereco            VARCHAR(500),
    ativo               BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_cli_cnpj ON clientes (cnpj);

CREATE TABLE IF NOT EXISTS cargas (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao           VARCHAR(500) NOT NULL,
    peso_kg             DOUBLE PRECISION,
    tipo                VARCHAR(50),
    volume_m3           DOUBLE PRECISION,
    nfe_chave           VARCHAR(50),
    cte_chave           VARCHAR(50),
    cliente_id          BIGINT ,
    criado_em           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_car_cliente ON cargas (cliente_id);
CREATE INDEX IF NOT EXISTS idx_car_tipo ON cargas (tipo);

-- =============================================================================
-- SEÇÃO 8 — MOTORISTAS E VEÍCULOS (entidades principais)
-- =============================================================================

CREATE TABLE IF NOT EXISTS motoristas (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           BIGINT  NOT NULL,
    nome                VARCHAR(255) NOT NULL,
    cpf                 VARCHAR(14) NOT NULL,
    cnh                 VARCHAR(20) NOT NULL,
    categoria_cnh       VARCHAR(5) NOT NULL,
    data_venc_cnh       DATE,
    data_venc_aso       DATE,
    mopp_valido         BOOLEAN DEFAULT FALSE,
    score               INT NOT NULL DEFAULT 1000,
    email               VARCHAR(200) UNIQUE,
    telefone            VARCHAR(20),
    ativo               BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- Constraints
    CONSTRAINT uk_motorista_cpf_tenant UNIQUE (cpf, tenant_id),
    CONSTRAINT uk_motorista_cnh UNIQUE (cnh)
);
CREATE INDEX IF NOT EXISTS idx_mot_cpf ON motoristas (cpf);
CREATE INDEX IF NOT EXISTS idx_mot_cnh ON motoristas (cnh);
CREATE INDEX IF NOT EXISTS idx_mot_tenant ON motoristas (tenant_id);
CREATE INDEX IF NOT EXISTS idx_mot_ativo ON motoristas (ativo);
CREATE INDEX IF NOT EXISTS idx_mot_score ON motoristas (score);
CREATE INDEX IF NOT EXISTS idx_mot_venc_cnh ON motoristas (data_venc_cnh);
CREATE INDEX IF NOT EXISTS idx_mot_venc_aso ON motoristas (data_venc_aso);

CREATE TABLE IF NOT EXISTS veiculos (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id               BIGINT  NOT NULL,
    placa                   VARCHAR(10) NOT NULL,
    modelo                  VARCHAR(255),
    marca                   VARCHAR(100),
    capacidade_carga        DOUBLE PRECISION,
    ano_fabricacao          INT,
    ativo                   BOOLEAN NOT NULL DEFAULT TRUE,
    cliente_id              BIGINT ,
    motorista_atual_id      BIGINT ,
    -- RN-VEI-002: Tacógrafo
    pbt_kg                  DOUBLE PRECISION,
    tacografo_obrigatorio   BOOLEAN DEFAULT FALSE,
    data_venc_tacografo     DATE,
    -- RN-VEI-003: Documentos com Vencimento
    data_venc_crlv          DATE,
    data_venc_seguro        DATE,
    data_venc_dpvat         DATE,
    data_venc_rcf           DATE,
    data_venc_vistoria      DATE,
    data_venc_rntrc         DATE,
    criado_em               TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- Constraints
    CONSTRAINT uk_veiculo_placa_tenant UNIQUE (placa, tenant_id)
);
CREATE INDEX IF NOT EXISTS idx_vei_placa ON veiculos (placa);
CREATE INDEX IF NOT EXISTS idx_vei_tenant ON veiculos (tenant_id);
CREATE INDEX IF NOT EXISTS idx_vei_ativo ON veiculos (ativo);
CREATE INDEX IF NOT EXISTS idx_vei_tacografo_venc ON veiculos (data_venc_tacografo);
CREATE INDEX IF NOT EXISTS idx_vei_crlv_venc ON veiculos (data_venc_crlv);
CREATE INDEX IF NOT EXISTS idx_vei_seguro_venc ON veiculos (data_venc_seguro);

-- =============================================================================
-- SEÇÃO 6 — ROTAS
-- =============================================================================

CREATE TABLE IF NOT EXISTS rotas (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                    VARCHAR(255) NOT NULL,
    origem                  VARCHAR(255),
    latitude_origem         DOUBLE PRECISION,
    longitude_origem        DOUBLE PRECISION,
    destino                 VARCHAR(255),
    latitude_destino        DOUBLE PRECISION,
    longitude_destino       DOUBLE PRECISION,
    distancia_prevista      DOUBLE PRECISION,
    tempo_previsto          INT,
    tolerancia_desvio_m     DOUBLE PRECISION DEFAULT 100.0,
    threshold_alerta_m      DOUBLE PRECISION DEFAULT 50.0,
    status                  VARCHAR(30) NOT NULL DEFAULT 'PLANEJADA',
    ativa                   BOOLEAN NOT NULL DEFAULT TRUE,
    data_inicio             TIMESTAMP,
    data_fim                TIMESTAMP,
    pontos_rota             JSON,
    veiculo_id              BIGINT ,
    motorista_id            BIGINT ,
    created_at              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_rot_veiculo ON rotas (veiculo_id);
CREATE INDEX IF NOT EXISTS idx_rot_motorista ON rotas (motorista_id);
CREATE INDEX IF NOT EXISTS idx_rot_status ON rotas (status);
CREATE INDEX IF NOT EXISTS idx_rot_ativa ON rotas (ativa);

-- =============================================================================
-- SEÇÃO 7 — VIAGENS
-- =============================================================================

CREATE TABLE IF NOT EXISTS viagens (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status                  VARCHAR(20) NOT NULL DEFAULT 'PLANEJADA',
    observacoes             TEXT,
    data_saida              TIMESTAMP,
    data_chegada_prevista   TIMESTAMP,
    data_chegada_real       TIMESTAMP,
    data_inicio             TIMESTAMP,
    distancia_real_km       DOUBLE PRECISION DEFAULT 0.0,
    km_fora_rota            DOUBLE PRECISION DEFAULT 0.0,
    score_viagem            INT DEFAULT 1000,
    veiculo_id              BIGINT ,
    motorista_id            BIGINT ,
    carga_id                BIGINT ,
    rota_id                 BIGINT ,
    created_at              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_via_veiculo ON viagens (veiculo_id);
CREATE INDEX IF NOT EXISTS idx_via_motorista ON viagens (motorista_id);
CREATE INDEX IF NOT EXISTS idx_via_rota ON viagens (rota_id);
CREATE INDEX IF NOT EXISTS idx_via_status ON viagens (status);
CREATE INDEX IF NOT EXISTS idx_via_saida ON viagens (data_saida);

-- =============================================================================
-- SEÇÃO 2 — TELEMETRIA PRINCIPAL
-- =============================================================================

CREATE TABLE IF NOT EXISTS telemetria (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    -- Identificação
    tenant_id                   BIGINT  NOT NULL,
    veiculo_id                  BIGINT  NOT NULL,
    veiculo_uuid                VARCHAR(36) NOT NULL,
    motorista_id                BIGINT ,
    viagem_id                   BIGINT ,
    device_id                   VARCHAR(64),
    imei_dispositivo            VARCHAR(20),

    -- LOCALIZAÇÃO GPS
    latitude                    DOUBLE PRECISION NOT NULL,
    longitude                   DOUBLE PRECISION NOT NULL,
    altitude                    DOUBLE PRECISION,
    velocidade                  DOUBLE PRECISION NOT NULL DEFAULT 0,
    direcao                     DOUBLE PRECISION,
    hdop                        DOUBLE PRECISION,
    satelites                   INT,
    precisao_gps                DOUBLE PRECISION,
    lat_snap                    DOUBLE PRECISION,
    lng_snap                    DOUBLE PRECISION,
    nome_via                    VARCHAR(255),

    -- MOTOR E DESEMPENHO
    ignicao                     BOOLEAN NOT NULL DEFAULT FALSE,
    rpm                         DOUBLE PRECISION NOT NULL DEFAULT 0,
    carga_motor                 DOUBLE PRECISION,
    torque_motor                DOUBLE PRECISION,
    temperatura_motor           DOUBLE PRECISION,
    pressao_oleo                DOUBLE PRECISION,
    tensao_bateria              DOUBLE PRECISION,
    odometro                    DOUBLE PRECISION NOT NULL DEFAULT 0,
    horas_motor                 DOUBLE PRECISION,
    aceleracao                  DOUBLE PRECISION,
    inclinacao                  DOUBLE PRECISION,

    -- COMBUSTÍVEL
    nivel_combustivel           DOUBLE PRECISION,
    consumo_combustivel         DOUBLE PRECISION,
    consumo_acumulado           DOUBLE PRECISION,
    tempo_ocioso                INT,
    tempo_motor_ligado          INT,

    -- COMPORTAMENTO DO MOTORISTA
    frenagem_brusca             BOOLEAN NOT NULL DEFAULT FALSE,
    numero_frenagens            INT NOT NULL DEFAULT 0,
    numero_aceleracoes_bruscas  INT NOT NULL DEFAULT 0,
    excesso_velocidade          BOOLEAN NOT NULL DEFAULT FALSE,
    velocidade_limite_via       DOUBLE PRECISION,
    curva_brusca                BOOLEAN NOT NULL DEFAULT FALSE,
    pontuacao_motorista         INT,

    -- EVENTOS DE SEGURANÇA
    colisao_detectada           BOOLEAN NOT NULL DEFAULT FALSE,
    geofence_violada            BOOLEAN NOT NULL DEFAULT FALSE,
    geofence_id                 BIGINT ,
    cinto_seguranca             BOOLEAN NOT NULL DEFAULT TRUE,
    porta_aberta                BOOLEAN NOT NULL DEFAULT FALSE,
    botao_panico                BOOLEAN NOT NULL DEFAULT FALSE,
    adulteracao_gps             BOOLEAN NOT NULL DEFAULT FALSE,
    impreciso                   BOOLEAN NOT NULL DEFAULT FALSE,
    preservar_dados             BOOLEAN NOT NULL DEFAULT FALSE,

    -- CARGA
    temperatura_carga           DOUBLE PRECISION,
    umidade_carga               DOUBLE PRECISION,
    peso_carga_kg               DOUBLE PRECISION,
    porta_bau_aberta            BOOLEAN NOT NULL DEFAULT FALSE,
    impacto_carga               BOOLEAN NOT NULL DEFAULT FALSE,
    g_force_impacto             DOUBLE PRECISION,

    -- PNEUS TPMS
    pressao_pneus_json          JSON,
    alerta_pneu                 BOOLEAN NOT NULL DEFAULT FALSE,

    -- CÂMERA DMS
    fadiga_detectada            BOOLEAN NOT NULL DEFAULT FALSE,
    distracao_detectada         BOOLEAN NOT NULL DEFAULT FALSE,
    uso_celular_detectado       BOOLEAN NOT NULL DEFAULT FALSE,
    cigarro_detectado           BOOLEAN NOT NULL DEFAULT FALSE,
    ausencia_cinto_dms          BOOLEAN NOT NULL DEFAULT FALSE,
    score_dms                   INT,

    -- AMBIENTE
    temperatura_externa         DOUBLE PRECISION,
    umidade_externa             DOUBLE PRECISION,
    chuva_detectada             BOOLEAN NOT NULL DEFAULT FALSE,
    condicao_pista              VARCHAR(30),

    -- CONECTIVIDADE
    sinal_gsm                   DOUBLE PRECISION,
    sinal_gps                   DOUBLE PRECISION,
    tecnologia_rede             VARCHAR(10),
    firmware_versao             VARCHAR(30),
    modo_offline                BOOLEAN NOT NULL DEFAULT FALSE,
    delay_sincronizacao_s       INT,

    -- TACÓGRAFO
    tacografo_status            VARCHAR(20),
    tacografo_velocidade        DOUBLE PRECISION,
    tacografo_distancia         DOUBLE PRECISION,
    horas_direcao_acumuladas    DOUBLE PRECISION,

    -- DESGASTE / MANUTENÇÃO
    manutencao_pendente         BOOLEAN NOT NULL DEFAULT FALSE,
    proxima_revisao             TIMESTAMP,
    desgaste_freio              DOUBLE PRECISION,
    dtc_codes                   JSON,

    -- PAYLOAD EXTENSÍVEL
    payload                     JSON,

    -- TIMESTAMPS
    data_hora                   TIMESTAMP NOT NULL,
    recebido_em                 TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processado_em               TIMESTAMP,

    PRIMARY KEY (id, data_hora)
);
CREATE INDEX IF NOT EXISTS idx_tel_veiculo_data ON telemetria (veiculo_id, data_hora DESC);
CREATE INDEX IF NOT EXISTS idx_tel_tenant_data ON telemetria (tenant_id, data_hora DESC);
CREATE INDEX IF NOT EXISTS idx_tel_viagem ON telemetria (viagem_id);
CREATE INDEX IF NOT EXISTS idx_tel_device ON telemetria (device_id);
CREATE INDEX IF NOT EXISTS idx_tel_data_hora ON telemetria (data_hora);
CREATE INDEX IF NOT EXISTS idx_tel_eventos ON telemetria (colisao_detectada, botao_panico, adulteracao_gps);
CREATE INDEX IF NOT EXISTS idx_tel_alertas ON telemetria (excesso_velocidade, frenagem_brusca, geofence_violada);
CREATE INDEX IF NOT EXISTS idx_tel_localizacao ON telemetria (latitude, longitude);
CREATE INDEX IF NOT EXISTS idx_tel_dms ON telemetria (fadiga_detectada, uso_celular_detectado);

-- =============================================================================
-- SEÇÃO 3 — ALERTAS E GEOFENCES
-- =============================================================================

CREATE TABLE IF NOT EXISTS geofences (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid             VARCHAR(36) NOT NULL UNIQUE DEFAULT (gen_random_uuid()::text),
    tenant_id        BIGINT  NOT NULL,
    nome             VARCHAR(255) NOT NULL,
    tipo             VARCHAR(50) NOT NULL DEFAULT 'CIRCULO',
    latitude_centro  DOUBLE PRECISION,
    longitude_centro DOUBLE PRECISION,
    raio             DOUBLE PRECISION,
    vertices         JSON,
    tipo_alerta      VARCHAR(50) NOT NULL DEFAULT 'AMBOS',
    aplica_todos     BOOLEAN NOT NULL DEFAULT TRUE,
    veiculos_uuid    JSON,
    ativo            BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_gf_tenant ON geofences (tenant_id);
CREATE INDEX IF NOT EXISTS idx_gf_ativo ON geofences (ativo);

CREATE TABLE IF NOT EXISTS veiculo_geofence (
    veiculo_id  BIGINT  NOT NULL,
    geofence_id BIGINT  NOT NULL,
    ativo       BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (veiculo_id, geofence_id)
);

CREATE TABLE IF NOT EXISTS alertas (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                    VARCHAR(36) NOT NULL UNIQUE DEFAULT (gen_random_uuid()::text),
    tenant_id               BIGINT  NOT NULL,
    veiculo_id              BIGINT ,
    veiculo_uuid            VARCHAR(36),
    motorista_id            BIGINT ,
    viagem_id               BIGINT ,
    telemetria_id           BIGINT,
    regra_id                BIGINT,
    tipo                    VARCHAR(80) NOT NULL,
    severidade              VARCHAR(50) NOT NULL DEFAULT 'MEDIO',
    categoria               VARCHAR(50),
    mensagem                TEXT NOT NULL,
    latitude                DOUBLE PRECISION,
    longitude               DOUBLE PRECISION,
    velocidade_kmh          DOUBLE PRECISION,
    odometro_km             DOUBLE PRECISION,
    nome_local              VARCHAR(255),
    dados_contexto          JSON,
    data_hora               TIMESTAMP NOT NULL,
    lido                    BOOLEAN NOT NULL DEFAULT FALSE,
    lido_por                VARCHAR(255),
    data_hora_leitura       TIMESTAMP,
    resolvido               BOOLEAN NOT NULL DEFAULT FALSE,
    resolvido_por           VARCHAR(255),
    data_hora_resolucao     TIMESTAMP,
    observacao_resolucao    TEXT,
    notificacao_enviada     BOOLEAN NOT NULL DEFAULT FALSE,
    canais_notificados      JSON,
    criado_em               TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_alerta_tenant ON alertas (tenant_id);
CREATE INDEX IF NOT EXISTS idx_alerta_veiculo ON alertas (veiculo_id);
CREATE INDEX IF NOT EXISTS idx_alerta_motorista ON alertas (motorista_id);
CREATE INDEX IF NOT EXISTS idx_alerta_viagem ON alertas (viagem_id);
CREATE INDEX IF NOT EXISTS idx_alerta_tipo ON alertas (tipo);
CREATE INDEX IF NOT EXISTS idx_alerta_severidade ON alertas (severidade);
CREATE INDEX IF NOT EXISTS idx_alerta_data ON alertas (data_hora);
CREATE INDEX IF NOT EXISTS idx_alerta_lido ON alertas (lido);
CREATE INDEX IF NOT EXISTS idx_alerta_resolvido ON alertas (resolvido);

-- =============================================================================
-- SEÇÃO 4 — DESVIOS DE ROTA
-- =============================================================================

CREATE TABLE IF NOT EXISTS desvios_rota (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id               BIGINT  NOT NULL,
    rota_id                 BIGINT  NOT NULL,
    veiculo_id              BIGINT  NOT NULL,
    veiculo_uuid            VARCHAR(36) NOT NULL,
    viagem_id               BIGINT ,
    latitude_desvio         DOUBLE PRECISION NOT NULL,
    longitude_desvio        DOUBLE PRECISION NOT NULL,
    velocidade_kmh          DOUBLE PRECISION,
    distancia_metros        DOUBLE PRECISION NOT NULL,
    lat_ponto_mais_proximo  DOUBLE PRECISION,
    lng_ponto_mais_proximo  DOUBLE PRECISION,
    nome_via_desvio         VARCHAR(255),
    data_hora_desvio        TIMESTAMP NOT NULL,
    data_hora_retorno       TIMESTAMP,
    duracao_min             INT,
    km_extras               DOUBLE PRECISION NOT NULL DEFAULT 0,
    alerta_enviado          BOOLEAN NOT NULL DEFAULT FALSE,
    resolvido               BOOLEAN NOT NULL DEFAULT FALSE,
    motivo                  VARCHAR(255),
    criado_em               TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_desvio_rota ON desvios_rota (rota_id);
CREATE INDEX IF NOT EXISTS idx_desvio_veiculo ON desvios_rota (veiculo_id);
CREATE INDEX IF NOT EXISTS idx_desvio_viagem ON desvios_rota (viagem_id);
CREATE INDEX IF NOT EXISTS idx_desvio_data ON desvios_rota (data_hora_desvio);
CREATE INDEX IF NOT EXISTS idx_desvio_resolvido ON desvios_rota (resolvido);

-- =============================================================================
-- SEÇÃO 5 — GEOCODING CACHE
-- =============================================================================

CREATE TABLE IF NOT EXISTS geocoding_cache (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat_arred       DECIMAL(7,4) NOT NULL,
    lng_arred       DECIMAL(7,4) NOT NULL,
    pais            VARCHAR(100),
    estado          VARCHAR(100),
    cidade          VARCHAR(200),
    bairro          VARCHAR(200),
    logradouro      VARCHAR(300),
    numero          VARCHAR(20),
    cep             VARCHAR(10),
    nome_local      VARCHAR(255),
    tipo_local      VARCHAR(50),
    is_urbano       BOOLEAN,
    precisao_metros INT,
    fonte           VARCHAR(50) NOT NULL DEFAULT 'NOMINATIM',
    consulta_em     TIMESTAMP NOT NULL,
    expira_em       TIMESTAMP NOT NULL,
    CONSTRAINT uk_geocoding_coords UNIQUE (lat_arred, lng_arred)
);
CREATE INDEX IF NOT EXISTS idx_geo_expira ON geocoding_cache (expira_em);

-- =============================================================================
-- SEÇÃO 9 — MANUTENÇÕES
-- =============================================================================

CREATE TABLE IF NOT EXISTS manutencoes (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_manutencao         DATE NOT NULL,
    descricao               TEXT NOT NULL,
    custo                   DOUBLE PRECISION,
    tipo                    VARCHAR(30) NOT NULL,
    oficina                 VARCHAR(100),
    km_realizacao           DOUBLE PRECISION,
    proxima_manutencao_km   DOUBLE PRECISION,
    proxima_manutencao_data DATE,
    observacoes             VARCHAR(500),
    veiculo_id              BIGINT  NOT NULL,
    motorista_id            BIGINT ,
    criado_em               TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_man_veiculo ON manutencoes (veiculo_id);
CREATE INDEX IF NOT EXISTS idx_man_data ON manutencoes (data_manutencao);
CREATE INDEX IF NOT EXISTS idx_man_tipo ON manutencoes (tipo);

-- =============================================================================
-- SEÇÃO 10 — USUÁRIOS
-- =============================================================================

CREATE TABLE IF NOT EXISTS usuarios (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login                   VARCHAR(100) NOT NULL UNIQUE,
    senha                   VARCHAR(255) NOT NULL,
    nome                    VARCHAR(255) NOT NULL,
    email                   VARCHAR(200) UNIQUE,
    cpf                     VARCHAR(14) NOT NULL UNIQUE,
    ativo                   BOOLEAN NOT NULL DEFAULT TRUE,
    perfil                  VARCHAR(20) NOT NULL,
    ultimo_acesso           TIMESTAMP,
    motorista_id            BIGINT  UNIQUE,
    -- RN-USR-001: Política de Senha
    data_expiracao_senha    DATE,
    tentativas_falha        INT DEFAULT 0,
    ultima_tentativa_falha  TIMESTAMP,
    bloqueado_ate           TIMESTAMP,
    -- RN-USR-002: MFA
    mfa_secret              VARCHAR(32),
    mfa_ativado             BOOLEAN DEFAULT FALSE,
    criado_em               TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_usr_login ON usuarios (login);
CREATE INDEX IF NOT EXISTS idx_usr_cpf ON usuarios (cpf);
CREATE INDEX IF NOT EXISTS idx_usr_email ON usuarios (email);
CREATE INDEX IF NOT EXISTS idx_usr_bloqueado_ate ON usuarios (bloqueado_ate);
CREATE INDEX IF NOT EXISTS idx_usr_data_expiracao_senha ON usuarios (data_expiracao_senha);

-- =============================================================================
-- SEÇÃO 11 — HISTÓRICO DE SENHAS
-- =============================================================================

CREATE TABLE IF NOT EXISTS historico_senhas (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id  BIGINT  NOT NULL,
    senha_hash  VARCHAR(255) NOT NULL,
    criado_em   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_hs_usuario ON historico_senhas (usuario_id);
CREATE INDEX IF NOT EXISTS idx_hs_criado_em ON historico_senhas (criado_em);

-- =============================================================================
-- SEÇÃO 12 — SESSÕES ATIVAS
-- =============================================================================

CREATE TABLE IF NOT EXISTS sessoes_ativas (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id      BIGINT  NOT NULL,
    token_jwt       VARCHAR(500) NOT NULL,
    ip              VARCHAR(45),
    user_agent      TEXT,
    data_criacao    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ultimo_acesso   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_expiracao  TIMESTAMP NOT NULL,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_sa_usuario ON sessoes_ativas (usuario_id);
CREATE INDEX IF NOT EXISTS idx_sa_token ON sessoes_ativas (token_jwt);
CREATE INDEX IF NOT EXISTS idx_sa_data_expiracao ON sessoes_ativas (data_expiracao);

-- =============================================================================
-- SEÇÃO 13 — HISTÓRICO DE SCORE DO MOTORISTA
-- =============================================================================

CREATE TABLE IF NOT EXISTS historico_score_motorista (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    motorista_id        BIGINT  NOT NULL,
    data                DATE NOT NULL,
    score_anterior      INT NOT NULL,
    score_novo          INT NOT NULL,
    diferenca           INT NOT NULL,
    motivo              VARCHAR(100),
    viagem_id           BIGINT,
    evento_tipo         VARCHAR(50),
    criado_em           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (motorista_id) REFERENCES motoristas(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_hsm_motorista ON historico_score_motorista (motorista_id);
CREATE INDEX IF NOT EXISTS idx_hsm_data ON historico_score_motorista (data);
CREATE INDEX IF NOT EXISTS idx_hsm_viagem ON historico_score_motorista (viagem_id);

-- =============================================================================
-- SEÇÃO 14 — AGREGAÇÕES E POSIÇÃO ATUAL
-- =============================================================================

CREATE TABLE IF NOT EXISTS resumo_diario_veiculo (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           BIGINT  NOT NULL,
    veiculo_id          BIGINT  NOT NULL,
    data                DATE NOT NULL,
    km_total            DOUBLE PRECISION NOT NULL DEFAULT 0,
    horas_uso           DOUBLE PRECISION NOT NULL DEFAULT 0,
    horas_ocioso        DOUBLE PRECISION NOT NULL DEFAULT 0,
    litros_consumidos   DOUBLE PRECISION NOT NULL DEFAULT 0,
    consumo_medio       DOUBLE PRECISION,
    velocidade_media    DOUBLE PRECISION,
    velocidade_maxima   DOUBLE PRECISION,
    frenagens_bruscas   INT NOT NULL DEFAULT 0,
    aceleracoes_bruscas INT NOT NULL DEFAULT 0,
    excessos_velocidade INT NOT NULL DEFAULT 0,
    curvas_bruscas      INT NOT NULL DEFAULT 0,
    total_alertas       INT NOT NULL DEFAULT 0,
    alertas_criticos    INT NOT NULL DEFAULT 0,
    total_viagens       INT NOT NULL DEFAULT 0,
    alertas_fadiga      INT NOT NULL DEFAULT 0,
    alertas_celular     INT NOT NULL DEFAULT 0,
    score_dia           INT NOT NULL DEFAULT 1000,
    total_eventos       INT NOT NULL DEFAULT 0,
    criado_em           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_resumo_veiculo_data UNIQUE (tenant_id, veiculo_id, data)
);
CREATE INDEX IF NOT EXISTS idx_rdv_tenant ON resumo_diario_veiculo (tenant_id);
CREATE INDEX IF NOT EXISTS idx_rdv_veiculo ON resumo_diario_veiculo (veiculo_id);
CREATE INDEX IF NOT EXISTS idx_rdv_data ON resumo_diario_veiculo (data);





CREATE TABLE IF NOT EXISTS posicao_atual (
    veiculo_id          BIGINT  NOT NULL PRIMARY KEY,
    tenant_id           BIGINT  NOT NULL,
    veiculo_uuid        VARCHAR(36) NOT NULL,
    latitude            DOUBLE PRECISION NOT NULL,
    longitude           DOUBLE PRECISION NOT NULL,
    velocidade          DOUBLE PRECISION NOT NULL DEFAULT 0,
    direcao             DOUBLE PRECISION,
    ignicao             BOOLEAN NOT NULL DEFAULT FALSE,
    status_veiculo      VARCHAR(30) NOT NULL DEFAULT 'DESCONHECIDO',
    motorista_id        BIGINT ,
    viagem_id           BIGINT ,
    odometro            DOUBLE PRECISION,
    nivel_combustivel   DOUBLE PRECISION,
    bateria_v           DOUBLE PRECISION,
    ultima_telemetria   TIMESTAMP NOT NULL,
    ultima_atualizacao  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    nome_local          VARCHAR(255),
    alertas_ativos      INT NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_pa_tenant ON posicao_atual (tenant_id);
CREATE INDEX IF NOT EXISTS idx_pa_status ON posicao_atual (status_veiculo);

CREATE TABLE IF NOT EXISTS historico_posicao (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT  NOT NULL,
    veiculo_id  BIGINT  NOT NULL,
    data_hora   TIMESTAMP NOT NULL,
    latitude    DOUBLE PRECISION NOT NULL,
    longitude   DOUBLE PRECISION NOT NULL,
    velocidade  DOUBLE PRECISION,
    ignicao     BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE INDEX IF NOT EXISTS idx_hp_veiculo ON historico_posicao (veiculo_id, data_hora DESC);
CREATE INDEX IF NOT EXISTS idx_hp_tenant ON historico_posicao (tenant_id);
CREATE INDEX IF NOT EXISTS idx_hp_data_hora ON historico_posicao (data_hora);







-- =============================================================================
-- SEÇÃO 15 — DISPOSITIVOS IoT
-- =============================================================================

CREATE TABLE IF NOT EXISTS dispositivos_iot (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id           VARCHAR(64) NOT NULL UNIQUE,
    imei                VARCHAR(20),
    iccid               VARCHAR(25),
    tenant_id           BIGINT ,
    veiculo_id          BIGINT ,
    tipo                VARCHAR(50) DEFAULT 'PRINCIPAL',
    fabricante          VARCHAR(100),
    modelo_hw           VARCHAR(100),
    versao_firmware     VARCHAR(30),
    versao_alvo         VARCHAR(30),
    certificado_cn      VARCHAR(100),
    certificado_expira  DATE,
    status_cert         VARCHAR(50) NOT NULL DEFAULT 'ATIVO',
    status              VARCHAR(50) NOT NULL DEFAULT 'PENDENTE',
    ultima_conexao      TIMESTAMP,
    ultimo_heartbeat    TIMESTAMP,
    ip_ultima_conexao   VARCHAR(45),
    tecnologia_rede     VARCHAR(10),
    rssi                DOUBLE PRECISION,
    freq_envio_s        INT NOT NULL DEFAULT 5,
    buffer_horas        INT NOT NULL DEFAULT 72,
    tem_satelite        BOOLEAN NOT NULL DEFAULT FALSE,
    iridium_imei        VARCHAR(20),
    satelite_ativo      BOOLEAN NOT NULL DEFAULT FALSE,
    observacoes         TEXT,
    instalado_em        DATE,
    instalado_por       VARCHAR(100),
    criado_em           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_disp_tenant ON dispositivos_iot (tenant_id);
CREATE INDEX IF NOT EXISTS idx_disp_veiculo ON dispositivos_iot (veiculo_id);
CREATE INDEX IF NOT EXISTS idx_disp_status ON dispositivos_iot (status);
CREATE INDEX IF NOT EXISTS idx_disp_imei ON dispositivos_iot (imei);

CREATE TABLE IF NOT EXISTS heartbeat_log (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id     VARCHAR(64) NOT NULL,
    tenant_id     BIGINT  NOT NULL,
    tipo          VARCHAR(50) NOT NULL,
    ip            VARCHAR(45),
    tecnologia    VARCHAR(10),
    rssi          DOUBLE PRECISION,
    firmware      VARCHAR(30),
    registrado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_hb_device ON heartbeat_log (device_id);
CREATE INDEX IF NOT EXISTS idx_hb_tenant ON heartbeat_log (tenant_id);
CREATE INDEX IF NOT EXISTS idx_hb_registrado ON heartbeat_log (registrado_em);

-- =============================================================================
-- SEÇÃO 16 — HISTÓRICO DE ODÔMETRO (RN-VEI-006)
-- =============================================================================

CREATE TABLE IF NOT EXISTS historico_odometro (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    veiculo_id              BIGINT  NOT NULL,
    dispositivo_origem_id   BIGINT,
    dispositivo_destino_id  BIGINT,
    odometro_anterior_km    DOUBLE PRECISION NOT NULL,
    odometro_novo_km        DOUBLE PRECISION NOT NULL,
    delta_km                DOUBLE PRECISION NOT NULL,
    data_troca              TIMESTAMP NOT NULL,
    usuario_id              BIGINT,
    observacao              TEXT,
    alerta_inconsistencia   BOOLEAN DEFAULT FALSE,
    criado_em               TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (veiculo_id) REFERENCES veiculos(id) ON DELETE CASCADE,
    FOREIGN KEY (dispositivo_origem_id) REFERENCES dispositivos_iot(id) ON DELETE SET NULL,
    FOREIGN KEY (dispositivo_destino_id) REFERENCES dispositivos_iot(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_ho_veiculo ON historico_odometro (veiculo_id);
CREATE INDEX IF NOT EXISTS idx_ho_data ON historico_odometro (data_troca);
CREATE INDEX IF NOT EXISTS idx_ho_delta ON historico_odometro (delta_km);

-- =============================================================================
-- SEÇÃO 17 — JORNADA (Lei 12.619/2012)
-- =============================================================================

CREATE TABLE IF NOT EXISTS jornadas (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id             BIGINT  NOT NULL,
    motorista_id          BIGINT  NOT NULL,
    veiculo_id            BIGINT ,
    viagem_id             BIGINT ,
    data_inicio           TIMESTAMP NOT NULL,
    data_fim              TIMESTAMP,
    horas_direcao         DOUBLE PRECISION NOT NULL DEFAULT 0,
    horas_disponivel      DOUBLE PRECISION NOT NULL DEFAULT 0,
    horas_repouso         DOUBLE PRECISION NOT NULL DEFAULT 0,
    horas_extras          DOUBLE PRECISION NOT NULL DEFAULT 0,
    pausas_realizadas     INT NOT NULL DEFAULT 0,
    km_rodados            DOUBLE PRECISION NOT NULL DEFAULT 0,
    limite_direcao_h      DOUBLE PRECISION NOT NULL DEFAULT 8.0,
    limite_extra_h        DOUBLE PRECISION NOT NULL DEFAULT 2.0,
    alertas_enviados      INT NOT NULL DEFAULT 0,
    alerta_limite_30min   BOOLEAN NOT NULL DEFAULT FALSE,
    status                VARCHAR(50) NOT NULL DEFAULT 'ABERTA',
    origem_dado           VARCHAR(50) NOT NULL DEFAULT 'TELEMETRIA',
    arquivo_tacografo     VARCHAR(200),
    irregular             BOOLEAN NOT NULL DEFAULT FALSE,
    motivo_irregularidade TEXT,
    criado_em             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_jornada_motorista ON jornadas (motorista_id);
CREATE INDEX IF NOT EXISTS idx_jornada_tenant ON jornadas (tenant_id);
CREATE INDEX IF NOT EXISTS idx_jornada_data ON jornadas (data_inicio);
CREATE INDEX IF NOT EXISTS idx_jornada_status ON jornadas (status);

-- =============================================================================
-- ADIÇÃO DAS CONSTRAINTS (FOREIGN KEYS) APÓS TODAS AS TABELAS CRIADAS
-- =============================================================================

ALTER TABLE cargas ADD CONSTRAINT fk_carga_cliente FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE SET NULL;

ALTER TABLE veiculos ADD CONSTRAINT fk_veiculo_cliente FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE SET NULL;
ALTER TABLE veiculos ADD CONSTRAINT fk_veiculo_motorista_atual FOREIGN KEY (motorista_atual_id) REFERENCES motoristas(id) ON DELETE SET NULL;

ALTER TABLE rotas ADD CONSTRAINT fk_rota_veiculo FOREIGN KEY (veiculo_id) REFERENCES veiculos(id) ON DELETE SET NULL;
ALTER TABLE rotas ADD CONSTRAINT fk_rota_motorista FOREIGN KEY (motorista_id) REFERENCES motoristas(id) ON DELETE SET NULL;

ALTER TABLE viagens ADD CONSTRAINT fk_viagem_veiculo FOREIGN KEY (veiculo_id) REFERENCES veiculos(id) ON DELETE SET NULL;
ALTER TABLE viagens ADD CONSTRAINT fk_viagem_motorista FOREIGN KEY (motorista_id) REFERENCES motoristas(id) ON DELETE SET NULL;
ALTER TABLE viagens ADD CONSTRAINT fk_viagem_carga FOREIGN KEY (carga_id) REFERENCES cargas(id) ON DELETE SET NULL;
ALTER TABLE viagens ADD CONSTRAINT fk_viagem_rota FOREIGN KEY (rota_id) REFERENCES rotas(id) ON DELETE SET NULL;

ALTER TABLE telemetria ADD CONSTRAINT fk_tel_veiculo FOREIGN KEY (veiculo_id) REFERENCES veiculos_cache(id) ON DELETE CASCADE;
ALTER TABLE telemetria ADD CONSTRAINT fk_tel_motorista FOREIGN KEY (motorista_id) REFERENCES motoristas_cache(id) ON DELETE SET NULL;

ALTER TABLE veiculo_geofence ADD CONSTRAINT fk_vgf_veiculo FOREIGN KEY (veiculo_id) REFERENCES veiculos_cache(id) ON DELETE CASCADE;
ALTER TABLE veiculo_geofence ADD CONSTRAINT fk_vgf_geofence FOREIGN KEY (geofence_id) REFERENCES geofences(id) ON DELETE CASCADE;

ALTER TABLE alertas ADD CONSTRAINT fk_alert_veiculo FOREIGN KEY (veiculo_id) REFERENCES veiculos_cache(id) ON DELETE SET NULL;
ALTER TABLE alertas ADD CONSTRAINT fk_alert_motorista FOREIGN KEY (motorista_id) REFERENCES motoristas_cache(id) ON DELETE SET NULL;

ALTER TABLE desvios_rota ADD CONSTRAINT fk_desvio_veiculo FOREIGN KEY (veiculo_id) REFERENCES veiculos_cache(id) ON DELETE CASCADE;

ALTER TABLE posicao_atual ADD CONSTRAINT fk_pa_veiculo FOREIGN KEY (veiculo_id) REFERENCES veiculos_cache(id) ON DELETE CASCADE;

ALTER TABLE historico_posicao ADD CONSTRAINT fk_hp_veiculo FOREIGN KEY (veiculo_id) REFERENCES veiculos_cache(id) ON DELETE CASCADE;

ALTER TABLE manutencoes ADD CONSTRAINT fk_manutencao_veiculo FOREIGN KEY (veiculo_id) REFERENCES veiculos(id) ON DELETE CASCADE;
ALTER TABLE manutencoes ADD CONSTRAINT fk_manutencao_motorista FOREIGN KEY (motorista_id) REFERENCES motoristas(id) ON DELETE SET NULL;

ALTER TABLE usuarios ADD CONSTRAINT fk_usuario_motorista FOREIGN KEY (motorista_id) REFERENCES motoristas(id) ON DELETE SET NULL;

ALTER TABLE jornadas ADD CONSTRAINT fk_jornada_motorista FOREIGN KEY (motorista_id) REFERENCES motoristas_cache(id) ON DELETE CASCADE;
ALTER TABLE jornadas ADD CONSTRAINT fk_jornada_veiculo FOREIGN KEY (veiculo_id) REFERENCES veiculos_cache(id) ON DELETE SET NULL;

-- =============================================================================
-- VIEWS ÚTEIS
-- =============================================================================

CREATE OR REPLACE VIEW vw_ultima_telemetria AS
SELECT t.*
FROM telemetria t
INNER JOIN (
    SELECT veiculo_id, MAX(data_hora) AS ultima_data
    FROM telemetria
    GROUP BY veiculo_id
) sub ON t.veiculo_id = sub.veiculo_id AND t.data_hora = sub.ultima_data;

CREATE OR REPLACE VIEW vw_frota_ao_vivo AS
SELECT
    pa.veiculo_id,
    pa.veiculo_uuid,
    pa.tenant_id,
    vc.placa,
    vc.modelo,
    vc.tipo_veiculo,
    pa.latitude,
    pa.longitude,
    pa.velocidade,
    pa.direcao,
    pa.ignicao,
    pa.status_veiculo,
    pa.odometro,
    pa.nivel_combustivel,
    pa.bateria_v,
    pa.ultima_telemetria,
    pa.alertas_ativos,
    pa.nome_local,
    mc.nome AS motorista_nome,
    pa.viagem_id
FROM posicao_atual pa
LEFT JOIN veiculos_cache   vc ON pa.veiculo_id  = vc.id
LEFT JOIN motoristas_cache mc ON pa.motorista_id = mc.id;

CREATE OR REPLACE VIEW vw_alertas_pendentes AS
SELECT
    a.*,
    vc.placa,
    mc.nome AS motorista_nome
FROM alertas a
LEFT JOIN veiculos_cache   vc ON a.veiculo_id   = vc.id
LEFT JOIN motoristas_cache mc ON a.motorista_id = mc.id
WHERE a.lido = FALSE
ORDER BY
    CASE a.severidade
        WHEN 'CRITICO' THEN 1
        WHEN 'ALTO'    THEN 2
        WHEN 'MEDIO'   THEN 3
        WHEN 'BAIXO'   THEN 4
    END,
    a.data_hora DESC;

-- =============================================================================
-- VIEW DE VEÍCULOS COM DOCUMENTOS VENCIDOS (RN-VEI-003)
-- =============================================================================

CREATE OR REPLACE VIEW vw_veiculos_documentos_vencidos AS
SELECT
    v.id,
    v.tenant_id,
    v.placa,
    v.modelo,
    v.marca,
    v.pbt_kg,
    v.tacografo_obrigatorio,
    v.data_venc_tacografo,
    v.data_venc_crlv,
    v.data_venc_seguro,
    v.data_venc_dpvat,
    v.data_venc_rcf,
    v.data_venc_vistoria,
    v.data_venc_rntrc,
    c.nome_razao_social AS tenant_nome,
    CASE
        WHEN v.data_venc_crlv < CURRENT_DATE THEN 'CRLV'
        WHEN v.data_venc_seguro < CURRENT_DATE THEN 'Seguro'
        WHEN v.data_venc_dpvat < CURRENT_DATE THEN 'DPVAT'
        WHEN v.data_venc_rcf < CURRENT_DATE THEN 'RCF'
        WHEN v.data_venc_vistoria < CURRENT_DATE THEN 'Vistoria'
        WHEN v.data_venc_rntrc < CURRENT_DATE THEN 'RNTRC'
        WHEN v.tacografo_obrigatorio = TRUE AND v.data_venc_tacografo < CURRENT_DATE THEN 'Tacógrafo'
        ELSE NULL
    END AS documento_vencido,
    LEAST(
        COALESCE(v.data_venc_crlv, (CURRENT_DATE + 999)),
        COALESCE(v.data_venc_seguro, (CURRENT_DATE + 999)),
        COALESCE(v.data_venc_dpvat, (CURRENT_DATE + 999)),
        COALESCE(v.data_venc_rcf, (CURRENT_DATE + 999)),
        COALESCE(v.data_venc_vistoria, (CURRENT_DATE + 999)),
        COALESCE(v.data_venc_rntrc, (CURRENT_DATE + 999)),
        COALESCE(v.data_venc_tacografo, (CURRENT_DATE + 999))
    ) AS proximo_vencimento
FROM veiculos v
INNER JOIN clientes c ON v.tenant_id = c.id
WHERE v.ativo = TRUE
  AND (
      v.data_venc_crlv < CURRENT_DATE OR
      v.data_venc_seguro < CURRENT_DATE OR
      v.data_venc_dpvat < CURRENT_DATE OR
      v.data_venc_rcf < CURRENT_DATE OR
      v.data_venc_vistoria < CURRENT_DATE OR
      v.data_venc_rntrc < CURRENT_DATE OR
      (v.tacografo_obrigatorio = TRUE AND v.data_venc_tacografo < CURRENT_DATE)
  );

-- =============================================================================
-- VIEW DE VEÍCULOS COM TACÓGRAFO VENCENDO EM 30/7 DIAS (RN-VEI-002)
-- =============================================================================

CREATE OR REPLACE VIEW vw_tacografo_proximo_vencimento AS
SELECT
    v.id,
    v.tenant_id,
    v.placa,
    v.modelo,
    v.pbt_kg,
    v.data_venc_tacografo,
    (v.data_venc_tacografo - CURRENT_DATE) AS dias_para_vencimento,
    c.nome_razao_social AS tenant_nome,
    CASE
        WHEN (v.data_venc_tacografo - CURRENT_DATE) <= 7 THEN 'CRITICO_7_DIAS'
        WHEN (v.data_venc_tacografo - CURRENT_DATE) <= 30 THEN 'ALERTA_30_DIAS'
        ELSE 'OK'
    END AS status_alerta
FROM veiculos v
INNER JOIN clientes c ON v.tenant_id = c.id
WHERE v.tacografo_obrigatorio = TRUE
  AND v.data_venc_tacografo IS NOT NULL
  AND v.data_venc_tacografo > CURRENT_DATE
  AND (v.data_venc_tacografo - CURRENT_DATE) <= 30;

-- =============================================================================
-- VIEW DE MOTORISTAS COM DOCUMENTOS VENCIDOS (RN-MOT-002 e RN-MOT-003)
-- =============================================================================

CREATE OR REPLACE VIEW vw_motoristas_documentos_vencidos AS
SELECT
    m.id,
    m.tenant_id,
    m.nome,
    m.cpf,
    m.cnh,
    m.categoria_cnh,
    m.data_venc_cnh,
    m.data_venc_aso,
    m.mopp_valido,
    m.score,
    c.nome_razao_social AS tenant_nome,
    CASE
        WHEN m.data_venc_cnh < CURRENT_DATE THEN 'CNH'
        WHEN m.data_venc_aso < CURRENT_DATE THEN 'ASO'
        WHEN m.mopp_valido = FALSE THEN 'MOPP'
        ELSE NULL
    END AS documento_vencido,
    LEAST(
        COALESCE(m.data_venc_cnh, (CURRENT_DATE + 999)),
        COALESCE(m.data_venc_aso, (CURRENT_DATE + 999))
    ) AS proximo_vencimento
FROM motoristas m
INNER JOIN clientes c ON m.tenant_id = c.id
WHERE m.ativo = TRUE
  AND (
      m.data_venc_cnh < CURRENT_DATE OR
      m.data_venc_aso < CURRENT_DATE OR
      m.mopp_valido = FALSE
  );



