CREATE TABLE IF NOT EXISTS regras_alerta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    nome VARCHAR(120) NOT NULL,
    tipo VARCHAR(80) NOT NULL,
    severidade VARCHAR(20) NOT NULL,
    campo VARCHAR(80) NOT NULL,
    operador VARCHAR(10) NOT NULL,
    valor_limite DOUBLE PRECISION NOT NULL,
    cooldown_minutos INT NOT NULL DEFAULT 5,
    canais JSON,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_regra_alerta_tenant_ativa ON regras_alerta (tenant_id, ativo);
