CREATE TABLE IF NOT EXISTS mdfe (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    viagem_id BIGINT NOT NULL,
    chave_mdfe VARCHAR(44) UNIQUE,
    status VARCHAR(20) NOT NULL,
    protocolo_autorizacao VARCHAR(100),
    data_emissao TIMESTAMP,
    data_encerramento TIMESTAMP,
    motivo_cancelamento TEXT,
    contingencia BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE INDEX IF NOT EXISTS idx_mdfe_viagem ON mdfe (viagem_id);

CREATE TABLE IF NOT EXISTS cte (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    carga_id BIGINT NOT NULL,
    chave_cte VARCHAR(44) NOT NULL UNIQUE,
    status VARCHAR(20) NOT NULL,
    valor_total DOUBLE PRECISION,
    peso_kg DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS ciot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    viagem_id BIGINT NOT NULL,
    motorista_id BIGINT NOT NULL,
    codigo_ciot VARCHAR(26) NOT NULL UNIQUE,
    valor_frete DOUBLE PRECISION,
    data_registro TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS rntrc_consultas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    rntrc VARCHAR(30) NOT NULL,
    situacao VARCHAR(20) NOT NULL,
    data_consulta TIMESTAMP NOT NULL,
    expira_em TIMESTAMP NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_rntrc_numero ON rntrc_consultas (rntrc);

CREATE TABLE IF NOT EXISTS mensagens_viagem (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    viagem_id BIGINT NOT NULL,
    remetente_uuid VARCHAR(36) NOT NULL,
    tipo_remetente VARCHAR(20) NOT NULL,
    conteudo TEXT NOT NULL,
    tipo_conteudo VARCHAR(20) NOT NULL,
    transcricao TEXT,
    lida BOOLEAN NOT NULL DEFAULT FALSE,
    criado_em TIMESTAMP NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_msg_viagem ON mensagens_viagem (viagem_id, criado_em);

CREATE TABLE IF NOT EXISTS ocorrencias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    tipo VARCHAR(40) NOT NULL,
    titulo VARCHAR(255) NOT NULL,
    descricao TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    raio_impacto_m DOUBLE PRECISION,
    fonte VARCHAR(30) NOT NULL,
    status VARCHAR(20) NOT NULL,
    previsao_liberacao TIMESTAMP,
    criado_em TIMESTAMP NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_ocorrencia_tenant_status ON ocorrencias (tenant_id, status);

CREATE TABLE IF NOT EXISTS sinistros (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    veiculo_id BIGINT NOT NULL,
    viagem_id BIGINT,
    motorista_id BIGINT,
    tipo VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    data_hora_ocorrencia TIMESTAMP NOT NULL,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    velocidade_no_momento DOUBLE PRECISION,
    telemetria_snapshot JSON,
    preservar_dados BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE INDEX IF NOT EXISTS idx_sinistro_tenant ON sinistros (tenant_id);

CREATE TABLE IF NOT EXISTS multas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    veiculo_id BIGINT NOT NULL,
    motorista_imputado_id BIGINT,
    auto_infracao VARCHAR(80) NOT NULL UNIQUE,
    data_infracao TIMESTAMP NOT NULL,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    velocidade_registrada DOUBLE PRECISION,
    velocidade_telemetria DOUBLE PRECISION,
    imputacao_confirmada BOOLEAN NOT NULL DEFAULT FALSE,
    valor_original DOUBLE PRECISION,
    vencimento_normal DATE,
    status VARCHAR(30) NOT NULL,
    contestacao_motivo TEXT
);
CREATE INDEX IF NOT EXISTS idx_multa_veiculo ON multas (veiculo_id);

CREATE TABLE IF NOT EXISTS vrp_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    tipo_vrp VARCHAR(30) NOT NULL,
    num_veiculos INT,
    num_pontos INT,
    solver_usado VARCHAR(40),
    tempo_execucao_ms BIGINT,
    plano_resultado JSON,
    criado_em TIMESTAMP NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_vrp_tenant_status ON vrp_jobs (tenant_id, status);

CREATE TABLE IF NOT EXISTS api_clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    client_id VARCHAR(100) NOT NULL UNIQUE,
    secret_hash VARCHAR(64) NOT NULL,
    plano VARCHAR(20) NOT NULL,
    scopes TEXT NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS webhooks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    evento VARCHAR(80) NOT NULL,
    url VARCHAR(500) NOT NULL,
    secret_hash VARCHAR(64) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    falhas_consecutivas INT NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_webhook_tenant ON webhooks (tenant_id);
